### ISSUE TITLE
Request for DR-HTF009S

### ISSUE THREAD

**Issue by lowema** [JeffSteinbok/hass-dreo#104]
Thanks for writing and supporting this integration, kudos to you !

Model - DR-HTF009S
Number of speeds the fan supports (not including "off") - 9
Does the fan support oscillating? YES
What preset modes are supported? Normal, Natural, Sleep, Auto
Is temperature supported? YES

Thanks
Mark

**Comment by JeffSteinbok** [comment]
Committed to main in #96

**Comment by Soukyuu** [comment]
I am confused, mine doesn't have the options:

<img width="1440" height="3120" alt="Image" src="https://github.com/user-attachments/assets/5142cec3-0735-4976-95e9-77b7845a90b4" />

And yes, I'm using your integration, not the official one

**Comment by Soukyuu** [comment]
[config_entry-dreo-01KVJ9NEG60JYFD13MZ1YAM512.json](https://github.com/user-attachments/files/29159718/config_entry-dreo-01KVJ9NEG60JYFD13MZ1YAM512.json)

Even more confused: diag info lists mode etc
