### ISSUE TITLE
Vertical Angle starts at 0 instead of -15 for ‎DR-HAF003S

### ISSUE THREAD

**Issue by MalteMatthey** [JeffSteinbok/hass-dreo#106]
There is a small mistake with the ‎DR-HAF003S. It can point downwards (up to -15 deg) but the interval for the vertical angle of the integration is from 0 to 90 instead of from -15 to 90.

Great integration btw., thank you so much!

**Comment by JeffSteinbok** [comment]
ACK - I'll have a look. It's a bit non-trivial right now as the values for these ranges aren't set per fan model.

**Comment by Airblader** [comment]
I’m also running into this for my 04S. From a glance at the code I’d wonder if it isn’t enough to add specific entries into SUPPORTED_MODELS that specify a custom device range vertical_angle_range?

**Comment by JeffSteinbok** [comment]
That's an option and you can submit that PR. 

I would prefer to auto detect, which we can totally do, like how we do preset modes. I probably won't have time to get to it in the next month though.

**Comment by Airblader** [comment]
Thanks for the response <3 I might submit a PR doing that; I took a quick look at the data w.r.t auto-detecting, and please bear in mind I only kind of know what I'm doing here, but I am not sure this information even is in the data? I could find this, but it doesn't seem to contain the actual range:

```
            "verSwingAngle": {
              "startAngle": 150,
              "sweepAngle": 120,
              "stepAngle": 5,
              "dottedLines": [
                150,
                270
              ],
              "quickStep": [
                30,
                60,
                90,
                120
              ]
            }
```

**Comment by JeffSteinbok** [comment]
I would look in the initial call to get the device list, or easier, look at the test cases with sample responses and see if those angles appear. I know they do as the app doesn’t hardcode much at all

-Jeff

On Sep 12, 2024, at 10:24 AM, Ingo Bürk ***@***.***> wrote:

﻿

Thanks for the response <3 I might submit a PR doing that; I took a quick look at the data w.r.t auto-detecting, and please bear in mind I only kind of know what I'm doing here, but I am not sure this information even is in the data? I could find this, but it doesn't seem to contain the actual range:

            "verSwingAngle": {
              "startAngle": 150,
              "sweepAngle": 120,
              "stepAngle": 5,
              "dottedLines": [
                150,
                270
              ],
              "quickStep": [
                30,
                60,
                90,
                120
              ]
            }

**Comment by Airblader** [comment]
Yeah, that is the data I'm looking at; the JSON from the tests contains the same snippet. I think I found it, though:

```
                    "fixedAngle": {
                      "verAngle": 120,
                      "horAngle": 120,
                      "verZeroAngle": 30,
                      "horZeroAngle": 60,
                      "imgColumn": 9,
                      "imgRow": 9
                    },
```

IIUC this says the total vertical angle is 120 degrees (-30 to 90 = 120), and at 30 degrees it is at a zero position (level).

**Comment by JeffSteinbok** [comment]
That looks right. If we can extract that dynamically and have it feed into the Number entities, that’d be great.

**Comment by Airblader** [comment]
I got it working now, and filed a PR. I wasn't entirely sure what the best way was to bring this into the Number definitions, so I hope this makes sense to you. Let me know!

**Comment by JeffSteinbok** [comment]
@MalteMatthey can you please confirm if the beta works? If so, I will promote it.

**Comment by MalteMatthey** [comment]
Just tested it, and it's working perfectly with my DR-HAF003S.

Thank you @Airblader and of course @JeffSteinbok!
