### ISSUE TITLE
Allow angle control for oscillating

### ISSUE THREAD

**Issue by MalteMatthey** [JeffSteinbok/hass-dreo#107]
The ‎DR-HAF003S and many other fans support a feature, where the ventilator oscillates between set vertical and horizontal angles. This would be a great addition to the integration. At the moment you can only set a fix vertical and horizontal angle for the ventilator.

I'll attach some screenshots how you can do this in the app. The integration would need 4 more numbers to control this.

- Oscillating horizontal angle left
- Oscillating horizontal angle right
- Oscillating vertical angle top
- Oscillating vertical angle bottom

It would be superb to get this feature!

![Screenshot_2024-05-26-18-21-56-931_com hesung dreo](https://github.com/JeffSteinbok/hass-dreo/assets/116491333/1b517f41-ea3d-470d-9ee7-8d074d7c93ae)
![Screenshot_2024-05-26-18-21-49-922_com hesung dreo](https://github.com/JeffSteinbok/hass-dreo/assets/116491333/59cb6aed-077b-4518-9baa-f4b7f0c431cd)

**Comment by JeffSteinbok** [comment]
See 0.7.0
