### ISSUE TITLE
Fix Readme URLs

### ISSUE THREAD

**Issue by JeffSteinbok** [JeffSteinbok/hass-dreo#108]
@andy-cooper  - Can you please fix the bad URLs in the Readme.md that you added?

**Comment by andy-cooper** [comment]
Sorry - been out of town for several weeks on a mix of work and vacation. I'll get to this and the other thing in the next week or so.

**Comment by andy-cooper** [comment]
https://github.com/JeffSteinbok/hass-dreo/pull/128
