### ISSUE TITLE
Add Support for Polyfan 502S (DR-HPF002S)

### ISSUE THREAD

**Issue by harvindhillon** [JeffSteinbok/hass-dreo#112]
Support for Polyfan 502S
https://www.dreo.com/products/polyfan-502s-air-circulator-fan

From the logs currently:
2024-05-27 18:49:46.748 WARNING (SyncWorker_40) [pydreo] Unknown fan or heater model: DR-HPF002S

**Comment by pcfreakshow** [comment]
Model - DR-HPF002S
Number of speeds the fan supports (not including "off") - 8
Does the fan support oscillating? - Yes (-30 to +90 vertical, -60 to +60 horizontal)
What preset modes are supported? - Normal, Auto, Sleep, Natural, Turbo
Is temperature supported? - Yes

**Comment by WhyAydan** [comment]
I have added this to my personal instance and made a PR

https://github.com/JeffSteinbok/hass-dreo/pull/123

**Comment by WhyAydan** [comment]
@JeffSteinbok Would you be able to merge this for me :)

https://github.com/JeffSteinbok/hass-dreo/pull/123

**Comment by prvashisht** [comment]
The workflows `HACS Validation` and `hassfest Validation` run on main and beta branches with a schedule. Does @JeffSteinbok have to trigger them manually on these other branches before it can be merged? (alongside an approval)

**Comment by WhyAydan** [comment]
Yeah think so

**Comment by GentleHoneyLover** [comment]
@WhyAydan, @JeffSteinbok, now that the PR has been approved, any time indication on when the new integration version will be available via HACS? :) Can't wait to have my new fan added :)))

**Comment by JeffSteinbok** [comment]
I've merged to main. You can tell HACS to use the main branch. I'll publish a release once I do a few other things.
