### ISSUE TITLE
Add support for model(s): DR-HCF001S / CLF521S

### ISSUE THREAD

**Issue by 67jeffh** [JeffSteinbok/hass-dreo#118]
Include all of the following:
 - Model - DR-HCF001S
- Number of speeds the fan supports (not including "off") - 12
- Does the fan support oscillating? No
- What preset modes are supported? Fan - Normal, Natural, Sleep, Auto, Reverse; Led Light - stepless brightness (1% to 100%) and light temperatures (from 2700K warm yellow to 6500K cool white)
- Is temperature supported? No

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

[home-assistant_2024-06-14T13-32-54.150Z.log](https://github.com/user-attachments/files/15838839/home-assistant_2024-06-14T13-32-54.150Z.log)

**Comment by JeffSteinbok** [comment]
This is in 0.7.1 except for the light.
Light is tracked in #143
