### ISSUE TITLE
Add support for model(s): DR-HPF005S - Polyfan 715S

### ISSUE THREAD

**Issue by Kozmikal** [JeffSteinbok/hass-dreo#119]
Include all of the following:
 - Model - DR-HPF005S
- Number of speeds the fan supports (not including "off") - 10
- Does the fan support oscillating? Yes- 120 horizontal with 5 steps (120, 90, 60, 30, 0) and 85 vertical with 4 step settings (85, 60, 30, 0)
- What preset modes are supported? Normal, Auto, Turbo, Natural, Custom, Sleep
- Is temperature supported? Yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

There was no response from HA when I hit the download diagnostics button but I found this in the logs:

This error originated from a custom integration.

Logger: pydreo
Source: custom_components/dreo/pydreo/__init__.py:212
integration: Dreo (documentation, issues)
First occurred: 11:10:06 AM (1 occurrences)
Last logged: 11:10:06 AM

Unknown device model: DR-HPF005S

**Comment by killerdraft** [comment]
Oh nice, came here to request this.

**Comment by tieszenj** [comment]
Here are some logs of me button mashing every option I could find.

[home-assistant_home-assistant-67b9846d55-m9z77_home-assistant.log](https://github.com/user-attachments/files/16120864/home-assistant_home-assistant-67b9846d55-m9z77_home-assistant.log)

**Comment by tieszenj** [comment]
Let me know if you would like me to annotate what buttons I'm pressing in line, would love to help support this fan! Thank you for your hard work!

**Comment by cbeale** [comment]
+1 to this please

**Comment by JeffSteinbok** [comment]
Is in 0.7.1
