### ISSUE TITLE
DR-HTF001S No oscillating icon in card and not supported function 

### ISSUE THREAD

**Issue by d13g0m0nt3s** [JeffSteinbok/hass-dreo#121]
Hi, the oscillating icon for this device do not show in the card. The toggle works in the device integration but now showing in the card. When you active the toggle then the icon appears on the card and remains there if you turn off the device but I home assistant restart the button is gone
If you add the fan on a tile card and add the oscillation function and click on the icon HA shows that the fan do not support this service. Needs to active the toggle in the device integration to work again.

Sorry my English, not my language 

thanks for the integration and regards.

![IMG_1112](https://github.com/JeffSteinbok/hass-dreo/assets/153827691/b49f908a-a27d-4daa-be9e-e13a9d80a888)
![IMG_1113](https://github.com/JeffSteinbok/hass-dreo/assets/153827691/3210f109-b9f6-4a46-ab86-c5058341c444)
![IMG_1114](https://github.com/JeffSteinbok/hass-dreo/assets/153827691/aa7ba64f-f0ff-4859-8186-e9663be10bb1)

**Comment by JeffSteinbok** [comment]
Please look at what the device attributes are when the card works and when it doesn't.  You can see that under "Developer Tools/States".

**Comment by JeffSteinbok** [comment]
Thanks for the info. I'll have a look. 
My guess is that if it's not oscillating, the value is None, and then perhaps we assume oscillation isn't supported.
Can you please get the diagnostics and attach them to a reply here?  Both when it's working and not?

**Comment by fynnsb** [comment]
which diagnostics should I get I only know where to find the state attributes from the dev tools page which is what is in the other reply

also here is some further info after testing in home assistant 24.8.3:

home assistant shows
```
supported_features: 59
oscillating: false
```
after turning oscillation off through the card when it discovered it through manually switching oscillation on in device info menu it remembers that the device has oscillation and it will still work to turn oscillation back on through the card and device popup. however when only switching it on an off without interacting through the card or popup just using the device info menu it will forget it again and go back to supported_features: 57.

so this should summarize what happens:
- after each restart of home assistant the device goes to supported_features: 57 and not showing oscillation in state attributes
  -> in this state oscillation is not supported on the card or device popup
- when manually enabling oscillation using the switch in the device menu it goes to supported_features: 59 and oscillating: false
  -> in this state oscillation is supported by both the card and device popup
- when switching oscillation off through the card it stays at supported_features: 59 until a restart of home assistant
  -> in this state oscillation is supported by both the card and device popup
  -> an interaction with the switch in the device menu will not impact the supported_features: 59 in this state it will stay until a 
       restart of home assistant
- when switching oscillation off through the device menu switch it will go back to supported_features: 57
  -> in this state it is not supported in the card or device popup again

**Comment by JeffSteinbok** [comment]
Go to the Device page and from there, there should be a "Download Diagnostics" button.  
![image](https://github.com/user-attachments/assets/b22da03e-8ac8-4477-83a7-89b609cb1f84)

**Comment by fynnsb** [comment]
here are the diagnostics files:
one is while it is working (after enabling oscillation through device page) and one is after fresh home assistant restart where it is not working.

only changes made is removed some serial numbers and ids (replaced with ***REMOVED BY ME ***) and also removed a few custom components from the lists. rest of the file is not changed.

for your info, there are 2 fans of the same exact model in it both just named "Ventilator" both with same behavior.
(both working in first file, both not working in second file)

[diagnostics while working.json](https://github.com/user-attachments/files/16767328/diagnostics.while.working.json)
[diagnostics while not workingjson.json](https://github.com/user-attachments/files/16767392/diagnostics.while.not.workingjson.json)
