### ISSUE TITLE
Add support for model(s):  CLF521S ceiling fan

### ISSUE THREAD

**Issue by carloss66** [JeffSteinbok/hass-dreo#122]
Include all of the following:
- Model - DR-HCF001S / CLF521S 
- Number of speeds the fan supports (not including "off"): 12
- Does the fan support oscillating? - No
- What preset modes are supported? Normal, Natural, Sleep, Auto, and Reverse
- Is temperature supported? - No

I turned on the fan, increased and decreased the speed, turned on the lamp, increased and decreased the light intensity, changed the light color temperature, muted and unmuted the sound, and turned off the fan and light.

[config_entry-dreo-b4bf568e8f121818292de7e90ad5b7eb.json](https://github.com/user-attachments/files/15901329/config_entry-dreo-b4bf568e8f121818292de7e90ad5b7eb.json)

[dreo_ha_debug.log](https://github.com/user-attachments/files/15901344/dreo_ha_debug.log)

**Comment by shuneycutt** [comment]
Seconding this request. I just purchased two with the hope of having the fans supported by this integration.

**Comment by shuneycutt** [comment]
After messing around with ChatGPT I was able to update the integration to expose the fan speed control in Home Assistant. However, I'm stuck on with getting the light entity exposed.

Hoping this request bubbles to the top of the list. 

Thanks for all of your work!

**Comment by 67jeffh** [comment]
I'm trying to get this same fan to work in home assistant also. How did you get the integration to see the fan?  

Thank you!

**Comment by carloss66** [comment]
> I'm trying to get this same fan to work in home assistant also. How did you get the integration to see the fan?
> 
> Thank you!

You can edit the models.py file and add:
```
    "DR-HCF001S": DreoDeviceDetails(
        preset_modes=[FAN_MODE_NORMAL, FAN_MODE_NATURAL, FAN_MODE_SLEEP, FAN_MODE_AUTO],
        range = {SPEED_RANGE: (1, 12)}
    )
```
With that the fan partially works in HA. It is recognized, I can adjust the fan speed, but I can't turn it on/off or do anything with the light.

**Comment by JeffSteinbok** [comment]
Added in #142 - But no Light yet.  I'll add a note for that.

**Comment by 67jeffh** [comment]
> > I'm trying to get this same fan to work in home assistant also. How did you get the integration to see the fan?
> > Thank you!
> 
> You can edit the models.py file and add:
> 
> ```
>     "DR-HCF001S": DreoDeviceDetails(
>         preset_modes=[FAN_MODE_NORMAL, FAN_MODE_NATURAL, FAN_MODE_SLEEP, FAN_MODE_AUTO],
>         range = {SPEED_RANGE: (1, 12)}
>     )
> ```
> 
> With that the fan partially works in HA. It is recognized, I can adjust the fan speed, but I can't turn it on/off or do anything with the light.

Thank you!!

**Comment by 67jeffh** [comment]
> Added in #142 - But no Light yet. I'll add a note for that.

Thank you!!
