### ISSUE TITLE
Add support for model(s): Dreo Polyfan 502S

### ISSUE THREAD

**Issue by DracoGSJ** [JeffSteinbok/hass-dreo#124]
Model - DR-HPF002S

Number of speeds the fan supports (not including "off") - 8

Does the fan support oscillating? Yes, Horizontal and Vertical 

What preset modes are supported? - 3 (Standard, Turbo, Custom) plus 4 other within the ones above  (Normal, Auto, Sleep, Natural)

Is temperature supported? - Yea

Diagnostics:

[config_entry-dreo-01J26X3WQZJ67S305N3P2G9G8G-4.json](https://github.com/user-attachments/files/16119894/config_entry-dreo-01J26X3WQZJ67S305N3P2G9G8G-4.json)

**Comment by pedro639** [comment]
Yup waiting for this one. I was gonna create a request but just saw it!

**Comment by JeffSteinbok** [comment]
Should be in now!
