### ISSUE TITLE
DR-HAF001S does not support Turbo Mode. Results in no fan motor operation.

### ISSUE THREAD

**Issue by the-flying-toaster** [JeffSteinbok/hass-dreo#127]
## DR-HAF001S does not support Turbo Mode.

Using this preset in Home Assistant results in the fan operating with no fan speed(fan will still oscillate and appear to be on, but with no fan blade movement).

Pull Request https://github.com/JeffSteinbok/hass-dreo/pull/126 has been submitted to address this issue.

DR-HAF001S fully works as expected in Home Assistant after this change has been made and Home Assistant reloaded.

**Comment by JeffSteinbok** [comment]
This has been merged.
