### ISSUE TITLE
Add support for DR-HAF004S

### ISSUE THREAD

**Issue by matthewcbyington** [JeffSteinbok/hass-dreo#13]
Model: DR-HAF004S
Speeds: 9, and it also has a “Turbo” mode
Oscillating: Yes, both up and down and left and right
Preset modes: “Standard”, “Custom”, and “Turbo”
Temperature: Supported

![IMG_5150](https://github.com/JeffSteinbok/hass-dreo/assets/1623447/44e4c89b-c2e9-418c-8910-ad3a57785bf3)

**Comment by JeffSteinbok** [comment]
Ok, I'm going to have to get some more info from you.
Most of the mappings of capabilities to numerical values come back from one API, so I'll see if I can dump the output in the logs or something.  

It **MAY** already work if you set the log level to DEBUG and then, before the error that it doesn't support the fan, I think I'm dumping out the Dreo response.  If I am, can you send that to me?

**Comment by matthewcbyington** [comment]
@JeffSteinbok here you go sir!

Request:
`{
	"acceptLanguage": "en",
	"method": "devices",
	"pageNo": "1",
	"pageSize": "100"
}
`

Response:
`{
	"code": 0,
	"msg": "OK",
	"data": {
		"currentPage": 1,
		"pageSize": 100,
		"totalNum": 3,
		"totalPage": 1,
		"list": [
			{
				"deviceId": "1670524303038222337",
				"sn": "1572127914365333506-b8cb27cbccae9660:001:0000000000s",
				"brand": "Dreo",
				"model": "DR-HAF004S",
				"productId": "1572127914365333506",
				"productName": "Air Circulator",
				"deviceName": "Kitchen Fan",
				"shared": false,
				"series": null,
				"seriesName": "Falcon S",
				"controlsConf": {
					"template": "DR-HAF004S",
					"lottie": {
						"key": "poweron",
						"frames": [
							{
								"value": 0,
								"frame": [
									0
								]
							},
							{
								"value": 1,
								"frame": [
									2
								]
							}
						]
					},
					"cards": [
						{
							"type": 2,
							"title": "device_control_temp",
							"icon": "",
							"image": "",
							"url": "",
							"show": true
						},
						{
							"type": 6,
							"title": "device_settings_title",
							"icon": "ic_setting",
							"image": "",
							"url": "dreo://nav/device/setting?deviceSn=${sn}",
							"show": true,
							"key": "setting"
						}
					],
					"preference": [
						{
							"id": "200",
							"type": "Panel Sound",
							"title": "device_control_panelsound",
							"image": "ic_mute",
							"reverse": true,
							"cmd": "muteon"
						},
						{
							"id": "210",
							"type": "Light Detection",
							"title": "device_control_lightdetection",
							"image": "ic_lightsensoron",
							"reverse": false,
							"cmd": "lightsensoron"
						},
						{
							"id": "220",
							"type": "Child Lock",
							"title": "device_control_childlock",
							"image": "ic_child_lock",
							"reverse": false,
							"cmd": "childlockon"
						},
						{
							"id": "230",
							"type": "Oscillation Calibration",
							"title": "device_control_calibration",
							"image": "ic_osc_cal"
						},
						{
							"id": "240",
							"type": "Temperature Unit",
							"title": "device_control_temp_unit",
							"image": "ic_temp_unit"
						}
					],
					"control": [
						{
							"id": "100",
							"type": "Mode",
							"title": "device_mode",
							"items": [
								{
									"text": "device_fans_mode_straight",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_normal_wind",
									"imageColors": [
										"#D5D6D7",
										"#25D7E4"
									],
									"cmd": "mode",
									"value": 1
								},
								{
									"text": "device_fans_mode_natural",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_natural_wind",
									"imageColors": [
										"#D5D6D7",
										"#2CDD96"
									],
									"cmd": "mode",
									"value": 2
								},
								{
									"text": "device_control_mode_sleep",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_sleep_wind",
									"imageColors": [
										"#D5D6D7",
										"#6249DF"
									],
									"cmd": "mode",
									"value": 3
								},
								{
									"text": "device_control_mode_auto",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_auto_wind",
									"imageColors": [
										"#D5D6D7",
										"#0A80F5"
									],
									"cmd": "mode",
									"value": 4
								}
							]
						},
						{
							"id": "110",
							"type": "Speed",
							"title": "device_control_speed",
							"items": [
								{
									"text": "1",
									"cmd": "windlevel",
									"value": 1
								},
								{
									"text": "9",
									"cmd": "windlevel",
									"value": 9
								}
							]
						},
						{
							"id": "130",
							"type": "DPad",
							"step": 5
						}
					],
					"category": "Air Circulators",
					"version": {
						"minControlVer": "2.0.7",
						"minPairingVer": "2.0.7"
					},
					"updateMcuVersion": ""
				},
				"mainConf": {
					"isSmart": true,
					"isWifi": true,
					"isBluetooth": true,
					"isVoiceControl": true
				},
				"resourcesConf": {
					"imageSmallSrc": "https://resources.dreo-cloud.com/app/202302/15b4a846f9849144729e6d3a9fe6592d95.png",
					"imageFullSrc": "https://resources.dreo-cloud.com/app/202302/158b6be82ae48e45fbb41e8d73af5e32e8.zip"
				},
				"servicesConf": [
					{
						"key": "user_manual",
						"value": "https://resources.dreo-cloud.com/app/202302/15dd1913e68d1148188a8bf366feb0fd2f.pdf"
					}
				]
			},
			{
				"deviceId": "1565887390735765505",
				"sn": "1453300621256003586-7157cc6a36744f3daf043989af0f86dc",
				"brand": "Dreo",
				"model": "DR-HTF004S",
				"productId": "1453300621256003586",
				"productName": "Tower Fan",
				"deviceName": "Office Fan",
				"shared": false,
				"series": null,
				"seriesName": "Pilot Max S",
				"controlsConf": {
					"template": "DR-HTF004S",
					"lottie": {
						"key": "poweron",
						"frames": [
							{
								"value": 0,
								"frame": [
									0
								]
							},
							{
								"value": 1,
								"frame": [
									2
								]
							}
						]
					},
					"cards": [
						{
							"type": 2,
							"title": "device_control_temp",
							"icon": "",
							"image": "",
							"url": "",
							"show": true
						},
						{
							"type": 6,
							"title": "device_settings_title",
							"icon": "ic_setting",
							"image": "",
							"url": "dreo://nav/device/setting?deviceSn=${sn}",
							"show": true,
							"key": "setting"
						}
					],
					"preference": [
						{
							"id": "200",
							"type": "Panel Sound",
							"title": "device_control_panelsound",
							"image": "ic_mute",
							"reverse": false,
							"cmd": "voiceon"
						},
						{
							"id": "220",
							"type": "Light Detection",
							"title": "device_control_lightdetection",
							"image": "ic_lightsensoron",
							"reverse": false,
							"cmd": "lightsensoron"
						},
						{
							"id": "230",
							"type": "Temperature Unit",
							"title": "device_control_temp_unit",
							"image": "ic_temp_unit"
						}
					],
					"control": [
						{
							"id": "100",
							"type": "Mode",
							"title": "device_mode",
							"items": [
								{
									"text": "device_fans_mode_straight",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_normal_wind",
									"imageColors": [
										"#D5D6D7",
										"#25D7E4"
									],
									"cmd": "windtype",
									"value": 1
								},
								{
									"text": "device_fans_mode_natural",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_natural_wind",
									"imageColors": [
										"#D5D6D7",
										"#2CDD96"
									],
									"cmd": "windtype",
									"value": 2
								},
								{
									"text": "device_control_mode_sleep",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_sleep_wind",
									"imageColors": [
										"#D5D6D7",
										"#6249DF"
									],
									"cmd": "windtype",
									"value": 3
								},
								{
									"text": "device_control_mode_auto",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_auto_wind",
									"imageColors": [
										"#D5D6D7",
										"#0A80F5"
									],
									"cmd": "windtype",
									"value": 4
								}
							]
						},
						{
							"id": "110",
							"type": "Speed",
							"title": "device_control_speed",
							"items": [
								{
									"text": "1",
									"cmd": "windlevel",
									"value": 1
								},
								{
									"text": "12",
									"cmd": "windlevel",
									"value": 12
								}
							]
						},
						{
							"id": "120",
							"type": "Oscillation",
							"title": "device_control_oscillation",
							"items": [
								{
									"text": "30°",
									"cmd": "shakehorizonangle",
									"value": 30
								},
								{
									"text": "60°",
									"cmd": "shakehorizonangle",
									"value": 60
								},
								{
									"text": "90°",
									"cmd": "shakehorizonangle",
									"value": 90
								},
								{
									"text": "120°",
									"cmd": "shakehorizonangle",
									"value": 120
								}
							],
							"cmd": "shakehorizon"
						}
					],
					"category": "Tower Fan",
					"setting": [
						{
							"text": "Firmware Version",
							"image": "image.png",
							"value": "1.0.0",
							"url": "dreo://control"
						}
					]
				},
				"mainConf": {
					"isSmart": true,
					"isWifi": true,
					"isBluetooth": true,
					"isVoiceControl": true
				},
				"resourcesConf": {
					"imageSmallSrc": "https://resources.dreo-cloud.com/app/202212/2ffc957f92e8d4a619c2ec5e8e5788042.png",
					"imageFullSrc": "https://resources.dreo-cloud.com/app/202212/21ad3bcf9c6074c2998d7323cb1503cb3.zip"
				},
				"servicesConf": [
					{
						"key": "user_manual",
						"value": "https://resources.dreo-cloud.com/app/202302/1069bca6dc06bb4f2fac1961cbcb190d09.pdf"
					}
				]
			},
			{
				"deviceId": "1562591346261233665",
				"sn": "1453300621256003586-a09a41acd80747108653bd252dd9fb11",
				"brand": "Dreo",
				"model": "DR-HTF004S",
				"productId": "1453300621256003586",
				"productName": "Tower Fan",
				"deviceName": "Living Room Fan",
				"shared": false,
				"series": null,
				"seriesName": "Pilot Max S",
				"controlsConf": {
					"template": "DR-HTF004S",
					"lottie": {
						"key": "poweron",
						"frames": [
							{
								"value": 0,
								"frame": [
									0
								]
							},
							{
								"value": 1,
								"frame": [
									2
								]
							}
						]
					},
					"cards": [
						{
							"type": 2,
							"title": "device_control_temp",
							"icon": "",
							"image": "",
							"url": "",
							"show": true
						},
						{
							"type": 6,
							"title": "device_settings_title",
							"icon": "ic_setting",
							"image": "",
							"url": "dreo://nav/device/setting?deviceSn=${sn}",
							"show": true,
							"key": "setting"
						}
					],
					"preference": [
						{
							"id": "200",
							"type": "Panel Sound",
							"title": "device_control_panelsound",
							"image": "ic_mute",
							"reverse": false,
							"cmd": "voiceon"
						},
						{
							"id": "220",
							"type": "Light Detection",
							"title": "device_control_lightdetection",
							"image": "ic_lightsensoron",
							"reverse": false,
							"cmd": "lightsensoron"
						},
						{
							"id": "230",
							"type": "Temperature Unit",
							"title": "device_control_temp_unit",
							"image": "ic_temp_unit"
						}
					],
					"control": [
						{
							"id": "100",
							"type": "Mode",
							"title": "device_mode",
							"items": [
								{
									"text": "device_fans_mode_straight",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_normal_wind",
									"imageColors": [
										"#D5D6D7",
										"#25D7E4"
									],
									"cmd": "windtype",
									"value": 1
								},
								{
									"text": "device_fans_mode_natural",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_natural_wind",
									"imageColors": [
										"#D5D6D7",
										"#2CDD96"
									],
									"cmd": "windtype",
									"value": 2
								},
								{
									"text": "device_control_mode_sleep",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_sleep_wind",
									"imageColors": [
										"#D5D6D7",
										"#6249DF"
									],
									"cmd": "windtype",
									"value": 3
								},
								{
									"text": "device_control_mode_auto",
									"textColors": [
										"#D5D6D7",
										"#D5D6D7"
									],
									"image": "ic_auto_wind",
									"imageColors": [
										"#D5D6D7",
										"#0A80F5"
									],
									"cmd": "windtype",
									"value": 4
								}
							]
						},
						{
							"id": "110",
							"type": "Speed",
							"title": "device_control_speed",
							"items": [
								{
									"text": "1",
									"cmd": "windlevel",
									"value": 1
								},
								{
									"text": "12",
									"cmd": "windlevel",
									"value": 12
								}
							]
						},
						{
							"id": "120",
							"type": "Oscillation",
							"title": "device_control_oscillation",
							"items": [
								{
									"text": "30°",
									"cmd": "shakehorizonangle",
									"value": 30
								},
								{
									"text": "60°",
									"cmd": "shakehorizonangle",
									"value": 60
								},
								{
									"text": "90°",
									"cmd": "shakehorizonangle",
									"value": 90
								},
								{
									"text": "120°",
									"cmd": "shakehorizonangle",
									"value": 120
								}
							],
							"cmd": "shakehorizon"
						}
					],
					"category": "Tower Fan",
					"setting": [
						{
							"text": "Firmware Version",
							"image": "image.png",
							"value": "1.0.0",
							"url": "dreo://control"
						}
					]
				},
				"mainConf": {
					"isSmart": true,
					"isWifi": true,
					"isBluetooth": true,
					"isVoiceControl": true
				},
				"resourcesConf": {
					"imageSmallSrc": "https://resources.dreo-cloud.com/app/202212/2ffc957f92e8d4a619c2ec5e8e5788042.png",
					"imageFullSrc": "https://resources.dreo-cloud.com/app/202212/21ad3bcf9c6074c2998d7323cb1503cb3.zip"
				},
				"servicesConf": [
					{
						"key": "user_manual",
						"value": "https://resources.dreo-cloud.com/app/202302/1069bca6dc06bb4f2fac1961cbcb190d09.pdf"
					}
				]
			}
		]
	}
}`

**Comment by JeffSteinbok** [comment]
Ok, so I'm trying to take some guesses at what the commands needed to be sent for the oscillation and the turbo modes.
I'm going to go ahead and make a small tweak to the code so that I can log out the websocket messages we get back from Dreo even if you don't have a recognized device.  From that, I think I can sort things out.  I'll update soon.

**Comment by JeffSteinbok** [comment]
Ok, I published 0.1.1; you can go to HACS and Update Repository then upgrade.

- Turn on **debug** logging for **pydreo** and start up HA.
- Go to your Dreo app on your phone, and perform the various commands you want to be able to use in HA.  Dreo servers will send updates to the WebSocket i'm listening on.
- Go look at the logs, you should see something like the below.  Send me that, and if you can, how it maps to the actions you were performing.

```
2023-06-29 01:02:25,312 - pydreo - DEBUG - Received message for unknown or unsupported device. SN: 1582290393341964289-77f2977b24191a4a:001:0000000000b
2023-06-29 01:02:25,312 - pydreo - DEBUG - Message: {'method': 'control-report', 'devicesn': '1582290393341964289-77f2977b24191a4a:001:0000000000b', 'messageid': 'bdf23a1f-c8e1-4e22-8ad3-dc0cd5dfdc7c', 'timestamp': 1688025746, 'reported': {'windtype': 1}}
```
Let me know if these steps work well, and I'll add to the README

**Comment by matthewcbyington** [comment]
@JeffSteinbok I tried following the steps you outlined, I:

1) Updated the Dreo to the new version via HACS
2) Enabled debug logging
3) Restarted HA

Here's what my config looks like in configuration.yaml:

`## Dreo Fans ##
dreo:
  username: !secret dreo_username
  password: !secret dreo_password

fan:
  - platform: dreo

logger:
  logs:
    dreo: debug
    pydreo: debug`

However, upon restart, I didn't see the DEBUG logs you mentioned, even when controlling the fan from the Dreo app and refreshing the logs. I did look at "view all logs" to make sure I was getting debug output.

The failure to load is absent now (since you allowed the integration to start even for unsupported models), and I see the following in the "Repairs" section. I"ll keep digging to see if I missed the logs you referenced, but I don't see them.

<img width="638" alt="image" src="https://github.com/JeffSteinbok/hass-dreo/assets/1623447/75ff4b00-27dd-43f0-a19c-04f06593be90">

**Comment by matthewcbyington** [comment]
@JeffSteinbok OK I see, so seems like in your recent update, actually potentially the configuration.yaml entries are not relevant. I was able to click on that first error above (saying that it doesn't support YAML configuration), I got a modal prompt for username and password, entered them, and now it's loaded with my 2 fans showing (not the third, unsupported one). Does this mean I should/can remove the configuration.yaml entries that your README specified us to add, it's now available to setup from the UI? If so, awesome!

Okay, so here's the unsupported fan commands now that I got the integration loaded:

1) Increasing fan speed from 2 to 3
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': 'a0622395-7c9b-4c71-8bcf-77ba9c35fc1e', 'timestamp': 1688052910, 'reported': {'windlevel': 3}}

2) Going into Turbo mode
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': '0bdb6085-7bd5-4cb7-b921-e6568cbd77b2', 'timestamp': 1688053017, 'reported': {'mode': 5}}

3) Turning the fan off
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': '996b781e-f374-43ff-9bb2-6c8a705f4225', 'timestamp': 1688053052, 'reported': {'poweron': False}}

4) Turning the fan on:
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': 'd8e9918d-c920-4f95-92f1-538a1c212b09', 'timestamp': 1688053075, 'reported': {'poweron': True}}

5) Turning off horizontal oscillation
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': '1724a858-ee05-46a1-8eec-0510d6ba2859', 'timestamp': 1688053098, 'reported': {'oscmode': 2}}

6) Turning off vertical oscillation (so now both are off)
{'method': 'report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': 'b8ae4295-fa60-40cd-addd-b1386d86859f', 'timestamp': 1688053131, 'reported': {'fixedconf': '33,-23'}}

7) Turning back on horizontal oscillation
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': '0aa3dce9-2166-4db7-8ece-e9a627a05da0', 'timestamp': 1688053159, 'reported': {'oscmode': 1}}

8) Turning back on vertical oscillation (so both are on now)
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': 'b4c1d8f9-541f-41ca-8c37-aacfa5d392dd', 'timestamp': 1688053178, 'reported': {'oscmode': 3}}

9) Setting mode to "Auto"
{'method': 'control-report', 'devicesn': '1572127914365333506-b8cb27cbccae9660:001:0000000000s', 'messageid': 'cfe37e91-0045-4811-8ddc-12ce491b63d1', 'timestamp': 1688053201, 'reported': {'mode': 4}}

Thank you so much again, and I hope this is useful @JeffSteinbok !!

**Comment by JeffSteinbok** [comment]
Sorry for the confusion; I did have that in the release notes, for 0.1.1, but not 0.1.1.  To be safe, I'll add it to the readme just in case.
For the rest, I think that's what I need.  I'll put something together and you can try it out. 

The only thing I don't quite understand is #6.  Not sure what 33,-23 would mean here, unless that's the position it's being fixed at.  When you stop it, do you specify the position you want it to be?

Looks like oscmode:
- 1 == horizontal
- 2 == vertical
- 3 == both

I'm not sure if 0 would be off or not.

**Comment by matthewcbyington** [comment]
Jeff - we are taking the kiddo to Monterey bay aquarium today. I will have a delayed response to your above questions, but will certainly reply this weekend! Thank you!

**Comment by ProblemFactory** [comment]
I just tested on my side. fixedconf is indeed the angle of the fan. When both oscillation turned off, the fan will stop at the last position so it being set by the fixedconf command. I also set the angle manually and the same fixedconf command is being sent with the angle I set.

**Comment by matthewcbyington** [comment]
@JeffSteinbok I concur with @ProblemFactory (thank you, Xingwei!) that when you turn it off it just stays where it's at. Let me know if you need any other info.

In any aside, I noticed my other tower fan, stopped working with this recent update. It fails to call the service when adjusting the speed. I'm not Sure if this was a regression or an issue on my side. Let me know if you want me to open a new ticket for it.

[281472002470352] no close frame received or sent
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/framing.py", line 68, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 729, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.11/asyncio/streams.py", line 522, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 690, in _write_appdata
    self._do_write()
  File "/usr/local/lib/python3.11/asyncio/sslproto.py", line 699, in _do_write
    count = self._sslobj.write(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 930, in write
    return self._sslobj.write(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL] internal error (_ssl.c:2423)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 203, in async_set_percentage
    await self.hass.async_add_executor_job(self.set_percentage, percentage)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/fan.py", line 125, in set_percentage
    self.device.change_fan_speed(
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 113, in change_fan_speed
    self._send_command(WINDLEVEL_KEY, fan_speed)
  File "/config/custom_components/dreo/pydreo/pydreobasedevice.py", line 65, in _send_command
    self._dreo.send_command(self, params)
  File "/config/custom_components/dreo/pydreo/__init__.py", line 324, in send_command
    asyncio.run(self.ws.send(content))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 635, in send
    await self.ensure_open()
  File "/usr/local/lib/python3.11/site-packages/websockets/legacy/protocol.py", line 935, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: no close frame received or sent

**Comment by JeffSteinbok** [comment]
Try restarting HA.  If that works, then it is more than likely the websocket issue where it needs to be re-opened.   I'm seeing the same thing on mine after a time.

If it happens when you restart HA, then yeah, turn on debug logging and let's see what's going on.

**Comment by matthewcbyington** [comment]
@JeffSteinbok I confirmed a restarted works. So it sounds like it was the WS issue. Maybe it's possible to auto reconnect if needed? Anyways thanks for getting back to me!

**Comment by matthewcbyington** [comment]
Awesome, w.r.t the reconnect! Yeah, no rush, I'm sure you're busy! I sent you an email as well, not sure if you got it or not

**Comment by JeffSteinbok** [comment]
HomeAssistant Fan definition unfortunately does not support vertical oscillation.  
We would have to come up with some other switch to set the oscillation mode to anything other than ON/OFF.

See issue #23

**Comment by JeffSteinbok** [comment]
@matthewcbyington - try out version 0.2.0b2.

I'm not entirely sure I got the Oscillation stuff working.  Please try it and let me know.
If it doesn't work, I can try a few other guesses in a private branch.

Please try:
- Setting Oscillation via HA
- Setting Oscillation via DREO app and see if it reflects in HA

Unfortunately, the app uses certificate pinning, so on iOS, I'm unable to get a trace of the calls.  Relying on the work that @zyonse did

**Comment by JeffSteinbok** [comment]
Some of this has been added in #26 thanks to @betamike. 
Check out https://github.com/JeffSteinbok/hass-dreo/releases/tag/v0.3.0b1 to see if it works for you.

**Comment by matthewcbyington** [comment]
Thank you both!

**Comment by matthewcbyington** [comment]
@betamike @JeffSteinbok I hit this error upon restart when trying out 0.3.0b1:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/__init__.py", line 37, in async_setup_entry
    load_devices = await hass.async_add_executor_job(manager.load_devices)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 177, in load_devices
    proc_return = self._process_devices(device_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 149, in _process_devices
    deviceFan = PyDreoAirCirculatorFan(SUPPORTED_AIR_CIRCULATOR_FANS[model], dev, self)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreoaircirculatorfan.py", line 20, in __init__
    super().__init__(fan_definition, details, dreoManager)
TypeError: PyDreoBaseDevice.__init__() takes 3 positional arguments but 4 were given

**Comment by JeffSteinbok** [comment]
Unfortunately, I don't have an air circulator to test with. :(  Nor have I invested in UTs yet.  Probably should, right? :)

**Comment by JeffSteinbok** [comment]
@matthewcbyington Are you able to test this with a manual install or do you need a HACS release?  I think I have a fix, and committed it into Beta branch.  If you can sync and copy that over, let me know.  Else I'll try it out later today and make a release.

**Comment by matthewcbyington** [comment]
@JeffSteinbok I can do it manually. no problem. If you want an air circulator to test with let me know. I will happily purchase one for you as a "thank you" for your efforts on this integration. 100% serious and happy to order it today. Please let me know.

**Comment by JeffSteinbok** [comment]
Shoot me an email:  ***@***.***

**Comment by matthewcbyington** [comment]
@JeffSteinbok I tried to this morning. let me know if you got it? Your email address is redacted here on this site, but you had sent it to me in a PM on HA forum a few weeks ago. If you got the email, just shoot me a reply. Thanks!

**Comment by betamike** [comment]
Hey @JeffSteinbok @matthewcbyington I was out of town for a few days but I'm back and can also help debug.

**Comment by matthewcbyington** [comment]
@JeffSteinbok okay so I tested it. So far, pretty good! Observations:

1) The kitchen fan (the air circulator) now correctly loads and is control-able, so that's awesome!
2) Adjusting the speeds works great
3) Even though the unit is oscillating (both up and down and left and right), the "fan" card in Home Assistant does not indicate it's oscillating.
4) You cannot control the oscillation, it throws an error:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 814, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity fan.kitchen_fan does not support this service.

Obviously as we discussed this could just be an artifact that HA doesn't support vertical oscillation. So, no complaints here, I'm super happy to have it working and control the fan speed.

Thanks so much Jeff.

**Comment by JeffSteinbok** [comment]
Plan is to fix those bugs and add custom sensors and stuff to set those non-standard things. Will take a bit as I’m on vacation but that’s the plan.

-Jeff

On Jul 23, 2023, at 10:19 AM, Matthew Byington ***@***.***> wrote:

﻿

@JeffSteinbok<https://github.com/JeffSteinbok> okay so I tested it. So far, pretty good! Observations:

  1.  The kitchen fan (the air circulator) now correctly loads and is control-able, so that's awesome!
  2.  Adjusting the speeds works great
  3.  Even though the unit is oscillating (both up and down and left and right), the "fan" card in Home Assistant does not indicate it's oscillating.
  4.  You cannot control the oscillation, it throws an error:

Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
return await cast(
^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
return await service.entity_service_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 814, in entity_service_call
raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity fan.kitchen_fan does not support this service.

Obviously as we discussed this could just be an artifact that HA doesn't support vertical oscillation. So, no complaints here, I'm super happy to have it working and control the fan speed.

Thanks so much Jeff.
