### ISSUE TITLE
DR-HTF001S in Homebridge  switches don't give context

### ISSUE THREAD

**Issue by Flameancer** [JeffSteinbok/hass-dreo#131]
I was able to get my dreo fan added to Home Assistant as well as get it added to homekit using the built-in home assistant bridge. However when I view the fan entity in Apple Home it shows the fan itself but also four additional switches. These switches appear to correlate with the different fan modes as flipping a switch does change the fan mode on the actual fan itself, but there's not indication on what mode the switch is applied to. 
![IMG_1701](https://github.com/user-attachments/assets/e294df16-52da-4634-8990-dc49b77b6133)
![IMG_1702](https://github.com/user-attachments/assets/fd24f1ba-37e4-4618-a32b-54bb2eac51ef)

Is there a way to fix this within in dreo application on how these modes are supported or is this an issue with Homebridge or a limitation with fans on homekit?

**Comment by Flameancer** [comment]
I went ahead and also open an issue with homebridge as well. https://github.com/zyonse/homebridge-dreo/issues/51

**Comment by JeffSteinbok** [comment]
you probably need to open an issue with the HA HomeKit integration.
