### ISSUE TITLE
Add support for model(s): CF511S

### ISSUE THREAD

**Issue by jan1678** [JeffSteinbok/hass-dreo#132]
- Model: Smart Air Circulator Fan CF511S
- Number of speeds the fan supports (not including "off") : 4
- Does the fan support oscillating? Yes
- What preset modes are supported? Normal, Auto, Natural, custom, Sleep
- Is temperature supported? No

[config_entry-dreo-01J2YPDQRH29JR3YD9C8ZJN3XM.json](https://github.com/user-attachments/files/16256675/config_entry-dreo-01J2YPDQRH29JR3YD9C8ZJN3XM.json)

Thank you!

**Comment by JeffSteinbok** [comment]
Should be in now.
