### ISSUE TITLE
Add support for model(s): DR-HTF010S

### ISSUE THREAD

**Issue by techchad** [JeffSteinbok/hass-dreo#134]
Include all of the following:
 - Model - DR-HTF010S
- Number of speeds the fan supports (not including "off") - 12
- Does the fan support oscillating? Yes
- What preset modes are supported? 4
- Is temperature supported? Yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.
[config_entry-dreo-01J31P8G5P23MD22A9BGYNR24C.json](https://github.com/user-attachments/files/16276642/config_entry-dreo-01J31P8G5P23MD22A9BGYNR24C.json)

**Comment by JeffSteinbok** [comment]
Fixed in #142
