### ISSUE TITLE
Add support for model(s): DR-HPF001S

### ISSUE THREAD

**Issue by SL8R8R** [JeffSteinbok/hass-dreo#136]
Include all of the following:
 - Model - DR-HPF001S
- Number of speeds the fan supports (not including "off") - 8
- Does the fan support oscillating? - Yes
- What preset modes are supported? - 3 (Standard, Turbo, Custom) plus 4 other within the ones above (Normal, Auto, Sleep, Natural)
- Is temperature supported? - Yes

[config_entry-dreo-01J3EKC8VPGMVPHW16HRJRGSKK.json](https://github.com/user-attachments/files/16342794/config_entry-dreo-01J3EKC8VPGMVPHW16HRJRGSKK.json)

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

**Comment by JeffSteinbok** [comment]
Done in #129
