### ISSUE TITLE
Add support for model(s): DR-HPF005S

### ISSUE THREAD

**Issue by forshawn** [JeffSteinbok/hass-dreo#137]
Include all of the following:
- Model - DR-HPF005S
- Number of speeds the fan supports (not including "off") - 10
- Does the fan support oscillating? - Vertical and Horizontal  Oscillation
- What preset modes are supported? - Normal, Auto, Turbo and Natural Mode
- Is temperature supported? - Yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

**Comment by JeffSteinbok** [comment]
@forshawn please attach diagnostics requested.
thx

**Comment by JeffSteinbok** [comment]
I took a guess, check out 0.7.1 in a bit.  No sleep mode?
