### ISSUE TITLE
Add support for model(s): DR-HPF003S

### ISSUE THREAD

**Issue by dro-ex** [JeffSteinbok/hass-dreo#138]
Include all of the following:
 - Model - DR-HPF003S
 - Number of speeds the fan supports (not including "off") - 5
 - Does the fan support oscillating? - Yes
 - What preset modes are supported? - 'normal', 'natural', 'sleep', 'auto', 'turbo'
 - Is temperature supported? - Yes

[config_entry-dreo-01J3KYQYRYD9N78SQDYE68RGFK.json](https://github.com/user-attachments/files/16395747/config_entry-dreo-01J3KYQYRYD9N78SQDYE68RGFK.json)

Make sure you've installed this integration, then from the integration settings page, select Download Diagnostics and attach that file.

* Only thing missing is exposure of PRESETS, cannot get state of presets nor assign a preset

**Comment by JeffSteinbok** [comment]
I don't see that fan in your config you linked.  You sure it's not HAF003S?

**Comment by JeffSteinbok** [comment]
Should work as of #166
