### ISSUE TITLE
Add support for model(s): DR-HPF002S

### ISSUE THREAD

**Issue by haseat** [JeffSteinbok/hass-dreo#139]
Include all of the following:
 - Model - DR-HPF002S
 - Number of speeds the fan supports (not including "off") - 8
- Does the fan support oscillating? - yes
- What preset modes are supported? - 'normal', 'natural', 'sleep', 'auto', 'turbo'
- Is temperature supported? - yes

[config_entry-dreo-01J3SNC9CJWSFMS0E9KRVYW8DB.json](https://github.com/user-attachments/files/16399136/config_entry-dreo-01J3SNC9CJWSFMS0E9KRVYW8DB.json)

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

**Comment by Zerreth** [comment]
??? The DR-HPF002S is listed under supported devices (README > Compatibility > Air circulators), yet it isn't available in home assistant.

**Comment by PapiOrtiz** [comment]
I noticed that too... I ended up just modifying the Dreo config in my Home Assistant using the File Editor.

Basically just copied the changes I saw they were intending on making.
Now I can use the fan.

**Comment by JeffSteinbok** [comment]
Should be in 0.7.  If not, re-open.
