### ISSUE TITLE
Add support for model(s): PolyFan 513S/DR-HAF003S

### ISSUE THREAD

**Issue by modem7** [JeffSteinbok/hass-dreo#141]
Include all of the following:
 - Model: PolyFan 513S/DR-HAF003S
- Number of speeds the fan supports (not including "off"): 8-built in speeds, 12h on/off timer
- Does the fan support oscillating? Yes (120° horizontal, 105° vertical (omni-directional oscillation)) (horizontal starts at -15°)
- What preset modes are supported? Turbo Mode, Normal Mode, Natural Mode, Sleep Mode and Custom Mode
- Is temperature supported? Yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

Whilst most of the functions work, there is no manual speed adjustment, different modes, or the on/off timer. 

[config_entry-dreo-01J480A53WKDHN2WC5P0NP3XVT.json](https://github.com/user-attachments/files/16482390/config_entry-dreo-01J480A53WKDHN2WC5P0NP3XVT.json)

Fixing the speed adjustment should resolve #73.

**Comment by JeffSteinbok** [comment]
Done in #43

**Comment by JeffSteinbok** [comment]
Fixed in 0.5.1
