### ISSUE TITLE
Add support for ceiling fan lights.

### ISSUE THREAD

**Issue by JeffSteinbok** [JeffSteinbok/hass-dreo#143]
See issue #122 for log files and such.

**Comment by JeffSteinbok** [comment]
Attached PR should address.  Would appreciate if someone could check.

**Comment by 67jeffh** [comment]
I would be happy too, only I really don't know how to do that.  If you can point me in the right direction or the related terminology, I'll research and figure it out.

Thank you for all your work on this!!

**Comment by JeffSteinbok** [comment]
See https://github.com/hacs/integration/issues/4009 for info.
