### ISSUE TITLE
DR-HAF003S asymmetric swing

### ISSUE THREAD

**Issue by apocaliss92** [JeffSteinbok/hass-dreo#144]
Hi! Great integration, I bought this brand just for this one existing :)

The model DR-HAF003S has a functionality to set the swing in asymmetrical way, not sure how it is represented on the data, maybe with a starting point and a width
Would it be possible to have it on HA? This would open to beautiful scenarios where I can change the applied ventilator zone with a click!

![image](https://github.com/user-attachments/assets/a2cf39d2-0f06-4296-99cd-00559e62018c)

**Comment by JeffSteinbok** [comment]
Should be able to do it with angle top/bottoms:
![image](https://github.com/user-attachments/assets/a43708c5-232a-4ad4-89cf-abb2ed70dc00)
