### ISSUE TITLE
Add support for model: DR-HAP003S

### ISSUE THREAD

**Issue by UberMentch** [JeffSteinbok/hass-dreo#149]
Include all of the following:
 - Model - DR-HAP003S
- Number of speeds the fan supports (not including "off") - 18
- Does the fan support oscillating? - No
- What preset modes are supported? - Auto, Turbo, Sleep
- Is temperature supported? - No

[config_entry-dreo-01J4QD45JEWNHWQBE5YE1Z90MR.json](https://github.com/user-attachments/files/16534610/config_entry-dreo-01J4QD45JEWNHWQBE5YE1Z90MR.json)

**Comment by JeffSteinbok** [comment]
Air Purifiers are currently not supported.  I may be able to support it quickly as a fan though

**Comment by UberMentch** [comment]
Sure, let's see if it works

**Comment by JeffSteinbok** [comment]
If you're able to test out this branch via a commit hash in HACS, let me know if it works.
I may refactor this completely still; not sure.
