### ISSUE TITLE
Warnings re TURN_OFF/TURN_ON in HomeAssistant error log

### ISSUE THREAD

**Issue by pedro639** [JeffSteinbok/hass-dreo#154]
Hello everyone, this has been the latest logs from HA, is anyone else experiencing it?

> Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
> Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues

**Comment by matthewcbyington** [comment]
Yes, me as well. @JeffSteinbok just FYI (you may already be aware)

**Comment by JeffSteinbok** [comment]
When do you see this error?
Does everything work correctly?

**Comment by pedro639** [comment]
The error began when I updated to the last version of the integration and to há 2024.8.everything seems to work okay so far

**Comment by matthewcbyington** [comment]
@JeffSteinbok my results are similar to @pedro639 

I see the error on HA startup only after I updated to 2024.8.

The fans seem to work fine, no issues. Tested turn on, turn off, and adjust percentage.

**Comment by pedro639** [comment]
After the last hacs 2.0 and ha update still there:

```
Logger: homeassistant.components.fan
Source: components/fan/__init__.py:295
integration: Fan (documentation, issues)
First occurred: 10:57:44 AM (2 occurrences)
Last logged: 10:57:44 AM

Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
Entity None (<class 'custom_components.dreo.fan.DreoFanHA'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/jeffsteinbok/hass-dreo/issues
```

**Comment by GentleHoneyLover** [comment]
I confirm. The error shows up in the logs after each HA start. I’m on HASS 2024.8.2 and HACS 2.0…

**Comment by GentleHoneyLover** [comment]
Moreover, after updating the Dreo integration to v0.8.2, in addition to the `turn_off/turn_on method` error, a new error appears:

```
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/dreo/pydreo/__init__.py:19
integration: Dreo (documentation, issues)
First occurred: 10:16:27 (1 occurrences)
Last logged: 10:16:27

/config/custom_components/dreo/pydreo/pydreofan.py:122: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
```

<br><img width="983" alt="Screenshot 2024-08-28 at 10 19 53" src="https://github.com/user-attachments/assets/ea5672f5-ba6a-439c-82c4-233342f3daa8">
