### ISSUE TITLE
Question: Change Speed selection from percentage to 1-4 for HAF001S

### ISSUE THREAD

**Issue by SPQRBen** [JeffSteinbok/hass-dreo#155]
Hello, 

this is probably a really stupid question and I tried to google it and found some community post but I dont know where todo those and I was wondering if this is a preset that could be changed in the integration from you or something that I need todo in my local installation? 

BR
Benedikt

**Comment by JeffSteinbok** [comment]
HA supports percentages.
We map them to the supported numbers internally.
