### ISSUE TITLE
Add support for model(s):  PolyFan 513S/DR-HAF003S

### ISSUE THREAD

**Issue by modem7** [JeffSteinbok/hass-dreo#157]
- Model: PolyFan 513S/DR-HAF003S
- Number of speeds the fan supports (not including "off"): 8-built in speeds, 12h on/off timer
- Does the fan support oscillating? Yes (120° horizontal, 105° vertical (omni-directional oscillation) (horizontal starts at -15°))
- What preset modes are supported? Turbo Mode, Normal Mode, Natural Mode, Sleep Mode and Custom Mode
- Is temperature supported? Yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

Whilst most of the functions work, there is no manual speed adjustment, different modes, or the on/off timer. 

[config_entry-dreo-01J480A53WKDHN2WC5P0NP3XVT.json](https://github.com/user-attachments/files/16482390/config_entry-dreo-01J480A53WKDHN2WC5P0NP3XVT.json)

It seems that the speed and mode setting is still omitted from the available/exposed sensors. 

![image](https://github.com/user-attachments/assets/c4f4c8ca-2901-4a84-81eb-4ced9af7e24a)

**Comment by MalteMatthey** [comment]
The fan is supported by this integration. When you click on the first entity ("Bedroom Fan") with the on-off-toggle, you'll discover options for speed control and various modes.

As for the on/off timer, I think it isn't supported at the moment. However, you can achieve the same functionality using HomeAssistant automations.

The vertical angle starts at 0° (not -15°) for now. This is an open issue #106 and yet to be fixed.

![image](https://github.com/user-attachments/assets/22f61126-0d7f-4f07-9850-01569e4e1d52)

**Comment by modem7** [comment]
You are absolutely right, thank you and apologies!

I totally didn't look at the slider itself.

Sincerely appreciate the fast response!
