### ISSUE TITLE
Authentication Issue

### ISSUE THREAD

**Issue by Tukamok** [JeffSteinbok/hass-dreo#158]
Looks like with the latest version of Home Assistant and the new 2.0 update to HACS I'm seeing authentication errors.

This error originated from a custom integration.

Logger: pydreo
Source: custom_components/dreo/pydreo/__init__.py:298
integration: Dreo (documentation, issues)
First occurred: 7:28:42 PM (6 occurrences)
Last logged: 7:40:03 PM

Error logging in with username and password

I have verified that the user and password that I'm using are correct and valid.

**Comment by fouram** [comment]
Seconded. I get the following:

```Logger: dreo
Source: custom_components/dreo/__init__.py:40
integration: Dreo 
First occurred: 10:44:36 PM (1 occurrences)
Last logged: 10:44:36 PM
Unable to login to the dreo server

Logger: pydreo
Source: custom_components/dreo/pydreo/__init__.py:298
integration: Dreo 
First occurred: 10:44:36 PM (1 occurrences)
Last logged: 10:44:36 PM
Error logging in with username and password

Logger: pydreo
Source: custom_components/dreo/pydreo/helpers.py:167
integration: Dreo 
First occurred: 10:44:36 PM (1 occurrences)
Last logged: 10:44:36 PM
No response from API

**Comment by JeffSteinbok** [comment]
I doubt it would have anything to do with HACS as that's just the installer and the integration doesn't depend on it in any way.  I also have rebooted everything and see the issue too now.  I didn't see it earlier today and I haven't changed anything since.  

Does seem like they changed something in their API somewhere and broke this.

@zyonse  - Any chance you're seeing the same thing on yours?

**Comment by JeffSteinbok** [comment]
Reproduced this in my test app.  Getting a 403 Forbidden error back from auth.

**Comment by JeffSteinbok** [comment]
If anyone can get a trace from the app that would be great. Instructions are in the Contributing wiki.

**Comment by ahwman** [comment]
Same issue here and it seems to coincide with upgrading HACS to 2.0.

**Comment by Djahnke12** [comment]
Same issue here on HACS 1.34.0

**Comment by sharpsan** [comment]
Didn't have the issue until upgrading to HACS 2.0

**Comment by JeffSteinbok** [comment]
@sharpsan that's just coincidence.  They did something with the UserAgent they expect.
0.7.2 fixes it, but unsure for how long

**Comment by marcobeltempo** [comment]
> @sharpsan that's just coincidence.  They did something with the UserAgent they expect.
> 
> 0.7.2 fixes it, but unsure for how long

@JeffSteinbok I'm experiencing the same issue on 0.7.2

**Comment by JeffSteinbok** [comment]
You sure?  Can you double-check please and attach logs?
I have run my test app against what's in main at the moment and it's passing.

**Comment by marcobeltempo** [comment]
> You sure?  Can you double-check please and attach logs?
> 
> I have run my test app against what's in main at the moment and it's passing.

It was an issue with my password. When I created my account yesterday, I used a 22-character password. However, when I tried to reset my password today, I found that it only allows a maximum of 20 characters. It seems their login/password reset validation rules are different from their registration rules.
