### ISSUE TITLE
PyDreo should not have a dependency on HA

### ISSUE THREAD

**Issue by JeffSteinbok** [JeffSteinbok/hass-dreo#159]
A recent set of PRs included a dependency on HomeAssistant in PyDreo; that shouldn't be there.
I apologize I missed this in the code reviews.

@iRonin , @andy-cooper , your two changes added or updated this.  If either of you want to take a crack at fixing, that'd be great, else I'll take care of it.

**Comment by iRonin** [comment]
@JeffSteinbok happy to try to help if you point me to the right direction. I pretty much reused the existing code but maybe introduced some dependency on constants? Let me know what to look at.

**Comment by JeffSteinbok** [comment]
Basically, there are dependencies on constants from HA.  Even if the values happen to be the same, they need to be mapped from HA to PyDreo from the HA layer.  PyDreo should eventually move into a separate repo and have zero dependencies on HA.  Right now, it's there as a convenience.

**Comment by iRonin** [comment]
Thet could have been me. The plugin uses HA architecture so if anything the constants should be extracted as lightweight dependency for both HA core and plugins.
However it's been already heavily used in your plugin:

This could be me:
```
from homeassistant.components.climate import (
    FAN_ON, 
    FAN_OFF
)
```

but there's been heavier dependencies like this:

```
from homeassistant.config_entries import ConfigEntry
from homeassistant.const import (
    CONF_IP_ADDRESS,
    CONF_PASSWORD,
    EVENT_HOMEASSISTANT_STOP,
    Platform,
)
from homeassistant.core import Event, HomeAssistant
from homeassistant.exceptions import ConfigEntryAuthFailed, ConfigEntryNotReady
from homeassistant.helpers.device_registry import DeviceInfo
from homeassistant.helpers.entity import EntityDescription
from homeassistant.helpers.update_coordinator import (
    CoordinatorEntity,
    DataUpdateCoordinator,
    UpdateFailed,
)
```

**Comment by JeffSteinbok** [comment]
In what file is that?

**Comment by iRonin** [comment]
I did search for `from homeassistant`

**Comment by JeffSteinbok** [comment]
The only instances other than constants and one type are in the Dreo folder, which is ok.  It's just the PyDreo folder that's an issue.

https://github.com/search?q=repo%3AJeffSteinbok%2Fhass-dreo+homeassistant+path%3A%2F%5Ecustom_components%5C%2Fdreo%5C%2Fpydreo%5C%2F%2F&type=code

**Comment by JeffSteinbok** [comment]
@iRonin, @andy-cooper  please have a look at this branch.  I can't test heaters or AC so I may have broken things, but this is the general direction.

https://github.com/JeffSteinbok/hass-dreo/tree/infra/fixdeps

**Comment by JeffSteinbok** [comment]
@andy-cooper - For the heaters where you use angles for Swing Mode, is that what Dreo actually supports or does it support arbitrary angles?  If the preset angles are just a thing for the UX in HA, then we should move that up a level and expose just the angle number in PyDreo.

**Comment by andy-cooper** [comment]
Apologies for not seeing this sooner - took at look at the changes and they LGTM. Made a comment in the commit. 

Regarding the oscillation angles - as far as I understood from looking at the Dreo doc, the heaters themselves only support those particular angles; they don't support arbitrary angles.

**Comment by JeffSteinbok** [comment]
Thanks. I'll have another look and see what makes sense. It's a bit odd overloading swing mode and angle like this. Need to think about it a bit more.

**Comment by iRonin** [comment]
@JeffSteinbok there are some conflicts with my `chefmaker-support` branch which I'm using locally. I'll test all the changes once I have resolved the conflicts.

**Comment by JeffSteinbok** [comment]
I'm sure there are lots. :(  I also did a bunch of PyLint fixes. 
If you can send me the JSON blobs that Dreo sends back for your devices, that would be super-helpful.  I can inject them and see at least if I'm parsing right.

**Comment by JeffSteinbok** [comment]
@iRonin do you have some sample JSONs?  I'm trying to figure out exactly what to do with your WH739S and the angle.

**Comment by iRonin** [comment]
@JeffSteinbok I emailed it to you after your previous message

**Comment by iRonin** [comment]
The AC I've got supports only on/off oscillation, there are no angles.

**Comment by JeffSteinbok** [comment]
Ok, thanks.  Sorry, then it's @andy-cooper  that I need JSON from. :)

**Comment by iRonin** [comment]
In your new branch:
```
    def __init__(self, preset_modes: list[FanMode], deviceRanges: dict, hvac_modes: list[HVACMode] = None,
```

`deviceRanges` shouldn't be `device_ranges`?

**Comment by JeffSteinbok** [comment]
Yeah, lots is busted. 
I'm going to also auto-detect modes and speeds and simplify the config greatly.  So, don't bother looking yet.  I'll let you all know when it's ready for a good look.

**Comment by iRonin** [comment]
Too bad you didn't merge the existing PR's before these changes. Will be a lot of work for us to resolve conflicts. I had my Chef Maker branch ready and live on mine and someone else's.

**Comment by JeffSteinbok** [comment]
That’s unfortunate.
Are your PRs ready to go? If so, I could integrate them and deal with the forward merge.

-Jeff

On Aug 23, 2024, at 6:46 PM, Cyprian Kowalczyk ***@***.***> wrote:

﻿

Too bad you didn't merge the existing PR's before these changes. Will be a lot of work for us to resolve conflicts. I had my Chef Maker branch ready and live on mine and someone else's.

**Comment by iRonin** [comment]
You've got my devices json. I've been running it on https://github.com/JeffSteinbok/hass-dreo/pull/113 locally and there was another user who deployed my forked repo where this PR is on master.

**Comment by JeffSteinbok** [comment]
Ok. I bit off more than I can chew at the moment. Is your PR ready to merge? I'll do that first. @iRonin

**Comment by iRonin** [comment]
I'm AFK but yesterday it looked master was just one small commit ahead. I can merge master and test later today.

**Comment by JeffSteinbok** [comment]
Awesome. Let me know. I can pop on and merge it.

**Comment by JeffSteinbok** [comment]
Your change is merged.  Published a 0.8.0b1 release for you to test.  If all is good, I'll make a non-pre-release version.
Note that I still have to fix the HA dependency issue this thread was started for originally.

**Comment by iRonin** [comment]
Tested it locally and LGTM 👍🏻

**Comment by JeffSteinbok** [comment]
Awesome.  @andy-cooper  - I'll give you a bit longer, then I'll publish as non pre-release.

**Comment by andy-cooper** [comment]
Just tested against the main branch and everything seems to work fine for my heaters.
