### ISSUE TITLE
Add support for model(s): DR-HSH017S

### ISSUE THREAD

**Issue by jase0001** [JeffSteinbok/hass-dreo#164]
Hi your integration looks great!  If you get a chance can you look to add the DREO HS517S.  It is a wall space heater with 3 heat speeds and an ECO mode.    The device also has a non heat 'Fan' mode'.  Thank you so much. 

Include all of the following:
 - Model - HS517S
- Number of speeds the fan supports (not including "off") 3 Fan modes and Eco mode
- Does the fan support oscillating? No
- What preset modes are supported? H1 H2 H3 and Eco
- Is temperature supported? Yes (Wall Heater)
[config_entry-dreo-01J67PXAM1SZVAS65CMVPFEM8H.json](https://github.com/user-attachments/files/16751585/config_entry-dreo-01J67PXAM1SZVAS65CMVPFEM8H.json)

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

**Comment by JeffSteinbok** [comment]
@andy-cooper  can you have a look?
If you look at my recent PR #166, shoudl be able to maybe do same for heaters?

**Comment by jase0001** [comment]
Hi do you know if this model can be integrated?  If not i think i am going to return it. Many thanks in advance.

**Comment by JeffSteinbok** [comment]
I or @andy-cooper  can hopefully get to it, or you can. :)

**Comment by jase0001** [comment]
Thanks @JeffSteinbok - i wish i knew how to do it!

**Comment by JeffSteinbok** [comment]
I suspect this already works in my latest version/branch.
Check out the attached version

**Comment by jase0001** [comment]
@JeffSteinbok didn't work bud, but sincerest thanks for trying.  Good luck with the project

**Comment by JeffSteinbok** [comment]
What version did you try?
Send me logs or diagnostics from the 1.0.9b1 release.

**Comment by jase0001** [comment]
@JeffSteinbok  - Ah, i can only get v1.0.0b1 on HACS - that could be the reason then if you have updated 1.0.9b1 - that version is not showing yet. 


![DREO](https://github.com/user-attachments/assets/7f1b1da9-2cab-4370-af0f-74e5f42f7e4a)

**Comment by JeffSteinbok** [comment]
Sorry. Yes. Typo. 1.0.0b1.
Any logs or diagnostics?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jase0001** [comment]
Attached.  Integration states no devices or entities, so it's not finding the heater.  Thanks again in advance - i sincerely appreciate your help @JeffSteinbok 

[config_entry-dreo-01J740SN39Z1MEQ82S93DRYFRR.json](https://github.com/user-attachments/files/16911589/config_entry-dreo-01J740SN39Z1MEQ82S93DRYFRR.json)

**Comment by JeffSteinbok** [comment]
Ok, so I missed up and didn't get the right one in.  
Try 1.0.0b2

**Comment by jase0001** [comment]
@JeffSteinbok  Working brilliantly! Mate i can't thank you enough...!  Cheers for adding this device.
