### ISSUE TITLE
Home Assistant - Dreo integration Model DR-HPF002S Speed Control not available

### ISSUE THREAD

**Issue by DracoGSJ** [JeffSteinbok/hass-dreo#165]
Thanks for adding the DR-HPF002S to the Dreo Integration.

Everything is great apart from the fan speed control isn't available.

The DR-HPF002S has 8 speeds from 1 to 8

**Comment by JeffSteinbok** [comment]
Check out 0.8.1, it auto-detects this now.  
If it doesn't work, please send the diagnostics from HA

**Comment by DracoGSJ** [comment]
NOw running 0.8.3 and still no fan speed avaialable.

Diagnostics attached.... 
[config_entry-dreo-01J26X3WQZJ67S305N3P2G9G8G (1).json](https://github.com/user-attachments/files/16843351/config_entry-dreo-01J26X3WQZJ67S305N3P2G9G8G.1.json)

**Comment by JeffSteinbok** [comment]
Logs look like it detected the speed. Can you send me a screen show of what you see that you don't expect?
