### ISSUE TITLE
DR-HTF005S Fan Speed

### ISSUE THREAD

**Issue by lj-tms** [JeffSteinbok/hass-dreo#171]
I saw there was a request for this model with different information and no diagnostics at issue https://github.com/JeffSteinbok/hass-dreo/issues/137

- Model = DR-HPF005S
- Number of speeds the fan supports (not including "off") = 12
- Does the fan support oscillating? = Yes (Horizontal)
- What preset modes are supported? = Normal, Natural, Sleep, Auto
- Is temperature supported? = Yes

When setting fan speed to 100% in HA, fan speed indicated on unit is set to 9 (of 12).

[home-assistant_2024-08-27T23-59-08.478Z.log](https://github.com/user-attachments/files/16770784/home-assistant_2024-08-27T23-59-08.478Z.log)
[config_entry-dreo-01J6AZB6W0SNQBNX8CJQQ2Z45K.json](https://github.com/user-attachments/files/16770782/config_entry-dreo-01J6AZB6W0SNQBNX8CJQQ2Z45K.json)

**Comment by JeffSteinbok** [comment]
Can you try the latest version?  And I don't see HPF anywhere in your logs?

**Comment by lj-tms** [comment]
Apologies, I made a mistake. Model = DR-HTF005S

**Comment by JeffSteinbok** [comment]
Try the latest version. Does it just work? If not, please include diagnostics.

**Comment by lj-tms** [comment]
Hello, sorry if I'm missing something simple, I'm new to HA.

I've installed via the recommended HACS which shows version 0.8.2 when installing. When I go to Settings >  Devices > Dreo, it shows 0.1.3. Is this correct?

If so, then nothing has changed for me. I am able to control the fan with HA, but not able to set it at full speed. 

When setting the fan to 100% in HA, the fan speed is set to 9.  The DR-HTF005S supports up to speed 12.

Thank you.

[config_entry-dreo-01J6AZB6W0SNQBNX8CJQQ2Z45K.json](https://github.com/user-attachments/files/16811133/config_entry-dreo-01J6AZB6W0SNQBNX8CJQQ2Z45K.json)

**Comment by JeffSteinbok** [comment]
Ok, found it. 
There is a bug in the auto-detecting of fan speeds. This particular model has an extra config section that I'm not reading which looks to superscede the standard configs. 

What I'll do is hardcode the speed of this fan and see about fixing the logic.

**Comment by lj-tms** [comment]
Excellent, thank you! Apologies for mixing up the model number.

And thank you so much for making this integration!
