### ISSUE TITLE
DR-HAF004S Vertical Angle

### ISSUE THREAD

**Issue by angrycatmeowmeow** [JeffSteinbok/hass-dreo#173]
The vertical angle on this model goes from -30 to 90, but using the slider it can only be set from 0-90 even though it appears 0 might correspond to -30. This is different than how it's shown on the horizontal angle where it can be set to negative numbers.

![image](https://github.com/user-attachments/assets/8d381d51-4d00-4a76-88bf-dabc06bdd5b6)

**Comment by JeffSteinbok** [comment]
Duplicate of #106
