### ISSUE TITLE
KeyError: ‘fan_2in1_breeze’ during setup of Dreo integration

### ISSUE THREAD

**Issue by holstein13** [JeffSteinbok/hass-dreo#179]
I’m encountering a KeyError related to the fan_2in1_breeze preset mode when setting up the Dreo integration in Home Assistant. The integration fails to load correctly due to this error.

Here is the log file:
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 7:46:14 PM (1 occurrences)
Last logged: 7:46:14 PM

Error setting up entry [email] for dreo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/__init__.py", line 47, in async_setup_entry
    load_devices = await hass.async_add_executor_job(manager.load_devices)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 213, in load_devices
    proc_return = self._process_devices(device_list)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/__init__.py", line 170, in _process_devices
    device = PyDreoFan(SUPPORTED_FANS[model_prefix], dev, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 57, in __init__
    self._preset_modes = self.parse_preset_modes(details)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/pydreo/pydreofan.py", line 140, in parse_preset_modes
    text = FAN_MODE_STRINGS[text_id]
           ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'fan_2in1_breeze'

Environment:
	•	Home Assistant version: 2024.8.3
	•	Dreo integration version: 0.8.3
	•	Installation type: Home Assistant Yellow
	•	Python version: 3.12

Steps to Reproduce:
	1.	Install the Dreo custom component.
	2.	Configure the integration using my Dreo account.
	3.	Start Home Assistant.
	4.	The error occurs during the setup of the Dreo entry.

Expected Behavior:
The integration should load without errors, and the Dreo devices should be available in Home Assistant.

Additional Context:
The preset mode fan_2in1_breeze appears not recognized in the FAN_MODE_STRINGS dictionary in the pydreofan.py file. This may be causing the setup to fail.

**Comment by JeffSteinbok** [comment]
Can you please attach diagnostics and I can add it to my test list.

**Comment by holstein13** [comment]
I'd be happy to, but I don't know what diagnostics means in the context of Home Assistant.  Let me know what you mean by "diagnostics" and I'll run them and attach them.

I modified the constant.py file and added "fan_2in1_breeze": "2-in-1 Breeze Mode" to the FAN_MODE_STRINGS = { section and that worked to clear the problem.

**Comment by JeffSteinbok** [comment]
Thanks.  Can you please push a PR with that fix?
Also, for diagnostics, go to the device, there should be a "..." menu somehwere, there is a "Download Diagnostics" option.

**Comment by PHolstein1** [comment]
I submitted the Pull Request.  

I wasn't able to find the diagnostics menu.  Is it on the Dreo App or in Home Assistant?  I believe the problem relates to the Chefmaker device that I have on my account but is not being pulled into HA.

**Comment by JeffSteinbok** [comment]
It's in HomeAssistant under Setup -> Devices & Integrations -> Dreo
________________________________

**Comment by PHolstein1** [comment]
[config_entry-dreo-01J68SQ5P5BQJ72VJ30CD1DEPT.json](https://github.com/user-attachments/files/16901388/config_entry-dreo-01J68SQ5P5BQJ72VJ30CD1DEPT.json)
 Here you go.
