### ISSUE TITLE
Fan control Ceiling Fan DR-HCF001S / CLF521S broke in 1.0

### ISSUE THREAD

**Issue by jasonnovak** [JeffSteinbok/hass-dreo#194]
previous thread:
https://github.com/JeffSteinbok/hass-dreo/issues/147

When I install the new 1.0 if says my office fan entity is no longer available / it's disabled in UI.

I tried removing my account, rolling back to a backup for 0.8.3, re-installing, but once clean install the fan control entry doesn't appear at all, only the light and panel. I'm not sure if there is a better way to fully do a clean install

If I re-install the test build 72d0ad1 my fan control is working again

![1](https://github.com/user-attachments/assets/c89d8f54-185b-4e63-a435-ecbb1dcf540d)
![2](https://github.com/user-attachments/assets/01c9d7d7-11a5-4488-85a3-a736afe39258)
![3](https://github.com/user-attachments/assets/f14fb80c-5519-4fcd-a192-d2fde840178f)

**Comment by JeffSteinbok** [comment]
I'm really sorry about this. Logs if you can please?

**Comment by JeffSteinbok** [comment]
Found it.  Very sorry about that, clearly need an additional test. :(  
1.0.1 coming imminently.
