### ISSUE TITLE
Integration no accessable after 1.0 update

### ISSUE THREAD

**Issue by 67jeffh** [JeffSteinbok/hass-dreo#198]

**Comment by 67jeffh** [comment]
After I updated to 1.0.0 and then 1.0.0b, the fan entity is greyed out and not accessible
[home-assistant_2024-09-09T18-46-12.341Z.log](https://github.com/user-attachments/files/16935218/home-assistant_2024-09-09T18-46-12.341Z.log)
.

![image](https://github.com/user-attachments/assets/6e0ecc5e-75da-470d-8fd2-b2ddd70505b4)

**Comment by JeffSteinbok** [comment]
Try 1.0.2

**Comment by 67jeffh** [comment]
That did it!

I'll test it out more when I get home today.

Thank you Jeff!
