### ISSUE TITLE
Add support for model(s): DR-HTF010S

### ISSUE THREAD

**Issue by mikewren** [JeffSteinbok/hass-dreo#199]
Include all of the following:
 - Model - in the format used in the README.MD DR-HTF010S
- Number of speeds the fan supports (not including "off") 1 through 12 + off = 13
- Does the fan support oscillating? yes
- What preset modes are supported? unknown
- Is temperature supported? yes

Make sure you've installed this integration, then from the integration settings page, select **Download Diagnostics** and attach that file.

Fetching temperature works great currently, would also like to fetch pm2.5 (pm25) information.  Bonus points implementing an oscillating toggle. :)  Thanks!

[config_entry-dreo-01J6QAACQSGTFX9YVT1K5C1WP7.json](https://github.com/user-attachments/files/16936154/config_entry-dreo-01J6QAACQSGTFX9YVT1K5C1WP7.json)
[home-assistant_2024-09-09T20-10-47.307Z.log](https://github.com/user-attachments/files/16936155/home-assistant_2024-09-09T20-10-47.307Z.log)

**Comment by JeffSteinbok** [comment]
@mikewren  - Oscillation toggle should already exist in the Fan entity, does it not?

The pm25 info I will see what I can do.

**Comment by mikewren** [comment]
Not seeing oscillation.

![IMG_6568](https://github.com/user-attachments/assets/a8a6934b-3ff3-4941-af30-6ad3d3e2bef9)

**Comment by JeffSteinbok** [comment]
Click on the fan entity; it will display it in the UI and it's an attribute I think.

**Comment by BSBarrows** [comment]
Hi! I have the DR-HTF010S and would love the PM25  "Air quality" to be monitored and logged, did this ever get done? Thank you for the work on this!

**Comment by race41989** [comment]
I also have the DR-HTF010S. It would be great if they added the PM25 and also the ability to control osculation.

The device via the dero app also has independent control for fan speed and air filter speed.

If there is anything I can do at all to help get these in there please do let me know! I would be more than happy to assist or provide anything that is needed!
