### ISSUE TITLE
Degrees of Oscillation - Enhancement

### ISSUE THREAD

**Issue by hanley-development** [JeffSteinbok/hass-dreo#2]
I am working on the degrees of oscillation that the fan can handle for models like the DR-HTF004S. I have it working somewhat in my dev domain but need to get through some errors. I'll send you a pull request, if you can do some integration testing with the DR-HTF008S or DR-HTF001S to confirm I don't make a breaking change. : )

Thanks for starting this project!

**Comment by JeffSteinbok** [comment]
Happy to help when you have it ready. 
This repo is really quite as-hoc at the moment. No tests or processes yet. Hoping to get to that soonish.

**Comment by JeffSteinbok** [comment]
Some of this has been added in #26 thanks to @betamike. 
Check out https://github.com/JeffSteinbok/hass-dreo/releases/tag/v0.3.0b1 to see if it works for you.

**Comment by JeffSteinbok** [comment]
Check out the version in main and see if it works for you
