### ISSUE TITLE
New Model - DR-HAF001S

### ISSUE THREAD

**Issue by akuehner** [JeffSteinbok/hass-dreo#21]
Model - `DR-HAF001S`
Number of speeds the fan supports: `4`
Does the fan support oscilating? `Yes`
What preset modes are supported? `Standard` and `Custom`
    Under `Standard`: `Normal`, `Natural`, `Sleep`, `Auto`
Is temperature supported? `Yes`

**Comment by JeffSteinbok** [comment]
Completed in version 0.2.0b2.

**Comment by JeffSteinbok** [comment]
@akuehner - Can you please send me the logs per the README?  Something I need to confirm.

**Comment by JeffSteinbok** [comment]
Some of this has been added in #26 thanks to @betamike. 
Check out https://github.com/JeffSteinbok/hass-dreo/releases/tag/v0.3.0b1 to see if it works for you.

**Comment by akuehner** [comment]
Sorry I wasn't fast enough to get you the logs, but I installed the latest beta and the fan appears to be working successfully. Thanks!
