### ISSUE TITLE
Dreo Humidifier unavailable - Error while setting up dreo platform for humidifier

### ISSUE THREAD

**Issue by asheroto** [JeffSteinbok/hass-dreo#211]
**Model**: Dreo HM311S

This was working great for several days. Today I look at the dashboard and notice that the device is unavailable. Thinking that an update may have caused it to break.

[config_entry-dreo-651846c194d6a640e7ad22c0b739d488.json](https://github.com/user-attachments/files/17049180/config_entry-dreo-651846c194d6a640e7ad22c0b739d488.json)

![image](https://github.com/user-attachments/assets/d2c6f676-3cbe-4362-9564-02fd6eca47a2)

Logs:
```
2024-09-18 12:16:46.641 ERROR (MainThread) [homeassistant.components.humidifier] Error while setting up dreo platform for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/dreo/humidifier.py", line 48, in async_setup_entry
    _LOGGER.debug("Humidifier:async_setup_entry: Adding Humidifiers (%s)", humidifier_entities_ha.count())
                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: list.count() takes exactly one argument (0 given)
```

Dashboard:
![image](https://github.com/user-attachments/assets/f25eb8bb-0cb8-4f1a-a492-f13e34987504)

https://github.com/JeffSteinbok/hass-dreo/issues/60

**Comment by asheroto** [comment]
Also when creating an issue, I noticed that there isn't a GitHub template for troubleshooting, only device request. In hindsight I should have clicked "open blank issue".

**Comment by JeffSteinbok** [comment]
I'm about to jump on a plane, but pushed what I think will fix.  Pull from main to try it out.

**Comment by asheroto** [comment]
Indeed, version 1.2.2 fixes the problem. Thanks!
