### ISSUE TITLE
Dreo Air Purifier

### ISSUE THREAD

**Issue by nertwork** [JeffSteinbok/hass-dreo#22]
Dreo Air Purifier

Model - DR-HAP003S
Number of speeds the fan supports: 18
Does the fan support oscilating? No
What preset modes are supported? Auto, Turbo, Sleep
Under Standard:  Auto, Turbo, Sleep
Is temperature supported? No

**Comment by JeffSteinbok** [comment]
I can probably do the basics pretty quick, but since it's so different than the others, can you please follow the instructions in the readme and send me the requested logs?

**Comment by nertwork** [comment]
Sure - I will try this later today/tomorrow and get back to you. Thanks for contributing all this!

**Comment by JeffSteinbok** [comment]
Seeing no response...

**Comment by apocaliss92** [comment]
Hey @JeffSteinbok I will get this purifier around next week, would be fine for you if I'd leave the logs here in this issue? Or you prefer a new one

**Comment by JeffSteinbok** [comment]
It is already, no?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
