### ISSUE TITLE
Dreo fan on/off is disabled

### ISSUE THREAD

**Issue by jt6186** [JeffSteinbok/hass-dreo#229]
Somewhere along the line the power on/off entity is no longer provided.  If I manually turn on the fan I can turn on and off the oscillating feature through Home Assistant.  

If I click on my fan entity I get this error message "This entity is no longer being provided by the dreo integration."  

In the logs I have this error:

Logger: homeassistant.components.fan
Source: helpers/entity_platform.py:598
integration: Fan ([documentation](https://www.home-assistant.io/integrations/fan), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+fan%22))
First occurred: 9:03:56 AM (1 occurrences)
Last logged: 9:03:56 AM
Error adding entity None for domain fan with platform dreo

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 598, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 816, in _async_add_entity
    capabilities=entity.capability_attributes,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 391, in capability_attributes
    supported_features = self.supported_features_compat
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 436, in supported_features_compat
    features = self.supported_features
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dreo/dreofan.py", line 70, in supported_features
    supported_features = FanEntityFeature.SET_SPEED | FanEntityFeature.TURN_ON | FanEntityFeature.TURN_OFF
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'FanEntityFeature' has no attribute 'TURN_ON'

I'm running HA Core 2024.7.4  which I can't presently upgrade because the newer version completely broke the Alexa integration.

I have not tried removing and re-installing the hass-dreo integration, should that be my next step?

**Comment by JeffSteinbok** [comment]
This integration needs a newer HA version.  HACS config says it needs 2024.8.0
See #154 

If that's not the issue, please advise.
