### ISSUE TITLE
No Fan Speed or modes on DR-HAF003S

### ISSUE THREAD

**Issue by natn** [JeffSteinbok/hass-dreo#232]
The DR-HAF003S configures. Basic controls are present except for fan speed and mode selection.

I also cannot select the fan modes: Standard - Normal, Auto, Sleep and Nature; Turbo;  and the Custom speed and temperature bands.  However, custom could be largely replaced with HA automation once fan speeds are working.

<img width="244" alt="image" src="https://github.com/user-attachments/assets/42dea6ea-d290-4ebf-b094-a530ac0a9236">

**Comment by JeffSteinbok** [comment]
Click on "Dungeon Fan", it should be part of the Fan entity, not a seperate control.
