### ISSUE TITLE
DR-HAF004S Options not working 

### ISSUE THREAD

**Issue by jxbrown** [JeffSteinbok/hass-dreo#40]
I have the CF714S (DR-HAF004S) and the HA card does not show horizontal and vertical oscillating and the display off setting is not working on either. 

Here's the diag logs. Please let me know if you need anything else.

Thanks
[config_entry-dreo-9c7949c2fccc1f30d9fe2c8b0ef0cdbc.json.txt](https://github.com/JeffSteinbok/hass-dreo/files/12258044/config_entry-dreo-9c7949c2fccc1f30d9fe2c8b0ef0cdbc.json.txt)

**Comment by elalcalde** [comment]
I echo the above sentiment. Appreciate the work done to even make this compatible with HA but have the same Dreo fan and there are no options to adjust oscillation.

**Comment by JeffSteinbok** [comment]
Please attach the diagnostic logs from the integration.  I’ll have a look.
The options to adjust should be separate switches that are associated with the device.  You won’t find it in the default Fan entity or card.

From: Wigberto Maldonado ***@***.***>
Date: Wednesday, August 9, 2023 at 10:19 AM
To: JeffSteinbok/hass-dreo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [JeffSteinbok/hass-dreo] DR-HAF004S Options not working (Issue #40)

I echo the above sentiment. Appreciate the work done to even make this compatible with HA but have the same Dreo fan and there are no options to adjust oscillation.

**Comment by jxbrown** [comment]
@JeffSteinbok  - Here my diags again if that helps. 

[config_entry-dreo-9c7949c2fccc1f30d9fe2c8b0ef0cdbc.json (1).txt](https://github.com/JeffSteinbok/hass-dreo/files/12374072/config_entry-dreo-9c7949c2fccc1f30d9fe2c8b0ef0cdbc.json.1.txt)

**Comment by JeffSteinbok** [comment]
Try the version currently in "main".  You should be able to select it from the HACS dropdown.
Let me know

**Comment by jxbrown** [comment]
Usually HACS pops up and notifies you of a later version. Not seeing it with the Dreo integration. Can you share a screenshoot or a preferred upgrade method. Thanks.

**Comment by JeffSteinbok** [comment]
I haven't published a new release yet, I'm still trying some things out.
Can you please go to HACS, and select the option to "Redownload" the integration.  
Then select the "Main" version at the bottom of the list.

**Comment by JeffSteinbok** [comment]
> I echo the above sentiment. Appreciate the work done to even make this compatible with HA but have the same Dreo fan and there are no options to adjust oscillation.

Please try the version in "main" and let me know if it works.
You'll have to go to "redownload" and select the "main" version.

Once someone tells me it works ok, then I'll publish it.

**Comment by jxbrown** [comment]
Looks good. The vertical and horizontal controls are working independently. I like the sliders you added as well. Question: Is there a way to lock in the vertical angle while it's  Oscillating?  For example, if I set the vertical angel to 20 degrees it stays in that position. When I hit the  Oscillating button,  is does not keep the virtual angle. I believe it uses whatever the phone app setting is. 

Also the turn off display is not working on the new build. 

Thanks!!

**Comment by JeffSteinbok** [comment]
Can you open a new issue for the oscilating/angle issues?  And be specific on what you're doing and how it behaves. 

Turn off display was never working - it was shown in error.  You can delete that entity.  On this model, it's an adaptive brightness setting instead.

**Comment by JeffSteinbok** [comment]
Marking closed.
