### ISSUE TITLE
DR-HAF003S

### ISSUE THREAD

**Issue by criterion67** [JeffSteinbok/hass-dreo#43]
Model - DR-HAF003S
Number of speeds the fan supports- 8
Does the fan support oscillating? Yes
What preset modes are supported? Air circulator speed changes according to Temperature or Time
Is temperature supported? Yes

**Comment by JeffSteinbok** [comment]
THis should already be supported on the version in "main".  Can you try that?  And let me know if it works for you?

**Comment by JeffSteinbok** [comment]
Fixed in 0.5.1
