### ISSUE TITLE
DR-HTF007S no longer oscillates since 0.5.0

### ISSUE THREAD

**Issue by VOSsec** [JeffSteinbok/hass-dreo#46]
Hello everyone, since the 0.5.0 update, the oscillation function can no longer be activated on the NOMAD S (DR-HTF007S). Everything worked before.

Can u pls fix it? THX ❤️

https://github.com/JeffSteinbok/hass-dreo/assets/129999011/dd7be22c-569a-4ef1-88d1-adadc2505139

**Comment by JeffSteinbok** [comment]
Fixed in v0.5.1
