### ISSUE TITLE
Tower fan not on list

### ISSUE THREAD

**Issue by senbeiwabaka** [JeffSteinbok/hass-dreo#53]
Just got a Dreo fan that is not on the list. Information below. Let me know if you need anything else

Model: DR-HTF005S
Number of speeds: 1-9
Oscillation: yes
Presets: not entirely sure what is being asked. Would it be that it has auto, natural,  normal, and sleep mode?
Temperature support: yes

**Comment by JeffSteinbok** [comment]
Fixed in 0.6.1
