### ISSUE TITLE
Cannot add as intergration

### ISSUE THREAD

**Issue by tehbob** [JeffSteinbok/hass-dreo#56]
I've added the repo as a custom, downloaded the repo, restarted HA.  When trying to add the integration, it asks for my Dreo UN/PW.  I enter the same creds I use at dreo.com as well as the app, and it comes back saying "authentication failed".  If these are the wrong creds, which creds should I be using or what site can I validate the creds against?

**Comment by samabsalom** [comment]
I solved this by changing my dreo app password to an 8 digit password with no special characters.

**Comment by JeffSteinbok** [comment]
Good catch! I’ll put this in the README.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by schluchdebub** [comment]
> I solved this by changing my dreo app password to an 8 digit password with no special characters.

Unfortunately the work around doesn't work for me. Any advices how to solve or bypass the issue?

**Comment by JeffSteinbok** [comment]
Excellent
