### ISSUE TITLE
A big Thank You!

### ISSUE THREAD

**Issue by cannondale0815** [JeffSteinbok/hass-dreo#57]
Hi Jeff,

I just wanted to thank you for this integration! I specifically searched for a smart tower fan that would be supported in Home Assistant and is priced right, and came across your custom integration here. I then proceeded to use your Amazon link to purchase a DR-HTF007S. Two days later and I'm up and running with it in HA. 

Thank you so much for this, and keep up the good work!

-J

**Comment by JeffSteinbok** [comment]
Thanks!
