### ISSUE TITLE
add directional buttons?

### ISSUE THREAD

**Issue by btehan** [JeffSteinbok/hass-dreo#58]
Hello and thank you for making this!

I just recently got a DR-HAFO03S and was able to connect it to HA with your software.  I'm wondering, is it possible to add directional buttons so I can make small adjustments without needing to use the oscillation switches?

Thanks!

**Comment by JeffSteinbok** [comment]
Can you be more specific? What in the app can you do that the integration doesn't support?

**Comment by btehan** [comment]
In the Dreo app, once you turn the fan on, there is a dpad that you can use to turn the fan left, right, up, and down.  I find it easier to make small adjustments than toggling the oscillation switches.

**Comment by JeffSteinbok** [comment]
I thought I had angle support. No?
Send me the debug info per the readme.

-Jeff

On Sep 17, 2023, at 5:36 PM, btehan ***@***.***> wrote:

﻿

In the Dreo app, once you turn the fan on, there is a dpad that you can use to turn the fan left, right, up, and down. I find it easier to make small adjustments than toggling the oscillation switches.

**Comment by btehan** [comment]
Oh, okay.  Then maybe I'm not doing something right or should use some other kind of lovelace card to do what I'm looking for.  What card do you use to be able to change the direction of the fan without using oscillation?
[config_entry-dreo-30b02083cb17c78b346e9842fb0a887e.json.txt](https://github.com/JeffSteinbok/hass-dreo/files/12652862/config_entry-dreo-30b02083cb17c78b346e9842fb0a887e.json.txt)

**Comment by JeffSteinbok** [comment]
Go to the devices & integrations view, find the Dreo device.  There are some other controls you have to add.  They won’t be in the fan card itself.

On Sep 18, 2023, at 12:57 PM, btehan ***@***.***> wrote:



Oh, okay. Then maybe I'm not doing something right or should use some other kind of lovelace card to do what I'm looking for. What card do you use to be able to change the direction of the fan without using oscillation?
config_entry-dreo-30b02083cb17c78b346e9842fb0a887e.json.txt<https://github.com/JeffSteinbok/hass-dreo/files/12652862/config_entry-dreo-30b02083cb17c78b346e9842fb0a887e.json.txt>

**Comment by btehan** [comment]
![Screenshot_20230918-172600](https://github.com/JeffSteinbok/hass-dreo/assets/62584008/a0b50d2c-2ce3-416b-adf4-9c8b0ddcaf09)

This is all I'm seeing for controls on the device.

**Comment by btehan** [comment]
And this is what I have in the Dreo app.   It's the dpad like set of buttons at the bottom right.
![Screenshot_20230918-172723](https://github.com/JeffSteinbok/hass-dreo/assets/62584008/4e46d447-8a7b-46b5-b52b-15efa091fd9f)

**Comment by JeffSteinbok** [comment]
Ok, I’ll look at your diagnostics file and see what’s up.

From: btehan ***@***.***>
Date: Monday, September 18, 2023 at 3:27 PM
To: JeffSteinbok/hass-dreo ***@***.***>
Cc: Jeff Steinbok ***@***.***>, Comment ***@***.***>
Subject: Re: [JeffSteinbok/hass-dreo] add directional buttons? (Issue #58)

[Screenshot_20230918-172600]<https://user-images.githubusercontent.com/62584008/268787741-a0b50d2c-2ce3-416b-adf4-9c8b0ddcaf09.png>

This is all I'm seeing for controls on the device.

**Comment by btehan** [comment]
Thanks Jeff!

FYI, I've only done this part:

> the Diagnostics feature in HomeAssistant to get diagnostics from the integration. Sensitive info should be redacted automatically.

I looked around and I couldn't figure out these parts:

> This integration logs to two loggers as shown below. To get verbose logs, change the log level. Please have logs handy if you're reaching out for help.
> You also may consider enabling verbose logging for the websocket component.

**Comment by JeffSteinbok** [comment]
Please confirm this is still an issue.
There won't be any directional buttons, but you should have something like this:
![image](https://github.com/JeffSteinbok/hass-dreo/assets/7330767/1fb79c1f-61b5-40c1-934a-3617f70f8d06)
