### ISSUE TITLE
Limited options on DR-HAF004S & DR-HAF003S

### ISSUE THREAD

**Issue by ethan-dow** [JeffSteinbok/hass-dreo#59]
Thank you so much for this integration! I have two Dreo fans.

They both integrate, but they are importantly both missing the ability to adjust speed of the fan. 

The DR-HAF004Sh has 8 speeds - in the app they are labeled 1 through 9.

The DR-HAF003S has 7 speeds, labeled 1 through 8. 
The 003S is also missing a few features in comparison to the 004S integration
- The size of the oscillation for both X and Y axis
- A setting on the app called "auto display off"

**Comment by ethan-dow** [comment]
Can you explain exactly how to (a) enable logging and (b) access the logs that you request in the readme? I've attached the diagnostics file. 


[config_entry-dreo-7eef263f9f31db4c1182bfb0ceda643d.json.txt](https://github.com/JeffSteinbok/hass-dreo/files/12666226/config_entry-dreo-7eef263f9f31db4c1182bfb0ceda643d.json.txt)

**Comment by btehan** [comment]
> They both integrate, but they are importantly both missing the ability to adjust speed of the fan.
> The DR-HAF004Sh has 8 speeds - in the app they are labeled 1 through 9.
> The DR-HAF003S has 7 speeds, labeled 1 through 8.


The integration lets me change the speed on my DR-HAF003S, but it's a percentage, not a numeral. So could this be an answer to that part?

https://github.com/JeffSteinbok/hass-dreo/issues/35#issuecomment-1644976416

**Comment by ethan-dow** [comment]
Not for me. It might be because I have two fans (?)

![image](https://github.com/JeffSteinbok/hass-dreo/assets/77599006/4f53a386-7dfd-42de-adf1-7730fdb4a7b3)

**Comment by btehan** [comment]
Try tapping on "Bedroom fan".   The text, not the switch.  It should get you to something like this:

![Screenshot_20230919-164334](https://github.com/JeffSteinbok/hass-dreo/assets/62584008/42d44625-6a09-4150-8d82-5fef0911f55f)

**Comment by btehan** [comment]
But those angles that show on yours, those look like just what I need:

https://github.com/JeffSteinbok/hass-dreo/issues/58

**Comment by ethan-dow** [comment]
Oh nice. Fan speed is solved :)

**Comment by ethan-dow** [comment]
> But those angles that show on yours, those look like just what I need:
> 
> #58

Those have a different purpose than the d-pad in the dreo app. Those just tell the fan how far to oscillate. You can't position the fan directly using those sliders.

**Comment by btehan** [comment]
> > But those angles that show on yours, those look like just what I need:
> > #58
> 
> Those have a different purpose than the d-pad in the dreo app. Those just tell the fan how far to oscillate. You can't position the fan directly using those sliders.

Awwww shoot.   Hrmm

**Comment by ethan-dow** [comment]
> > > But those angles that show on yours, those look like just what I need:
> > > #58
> > 
> > 
> > Those have a different purpose than the d-pad in the dreo app. Those just tell the fan how far to oscillate. You can't position the fan directly using those sliders.
> 
> Awwww shoot. Hrmm

Kind of a crappy workaround but one could enable oscillation until the fan is where you want it to be and then disable oscillation.

**Comment by JeffSteinbok** [comment]
You SHOULD be able to position the fan from the angle sliders.  It doesn't control the oscilation ranges, jsut the actual angles.  If that's not what's happening, then let me know.

**Comment by ethan-dow** [comment]
I stand corrected, that feature is working on the 004
________________________________

**Comment by ethan-dow** [comment]
@btehan Do you experience the following issue?
When the fans are turned on, they default to their last used settings. From what I can tell, turning the fan on twice will enable the settings selected in HA.

**Comment by btehan** [comment]
> @btehan Do you experience the following issue? When the fans are turned on, they default to their last used settings. From what I can tell, turning the fan on twice will enable the settings selected in HA.

As far as I've seen, the fan turns on with the settings as they are in HA.

**Comment by derailius** [comment]
I'm sorry for my ignorance, but if i'm reading this right, you're saying that there is no way to add the angles for DR-HAF003S?

**Comment by scrampker** [comment]
DR-HAF003S doesn't seem to expose angles. I'd KILL to be able to use my FP2 granular location data to move the fan to my desk, to my bed, or put it back in wide-angle oscillation.

**Comment by scrampker** [comment]
I've tried to delete integration, re-discover, etc and all I get is the following:
![image](https://github.com/JeffSteinbok/hass-dreo/assets/15056860/90829773-fb76-4296-96e8-6490e2db7297)

Any ideas?

**Comment by fadudba** [comment]
Hi, I have a HAF003s, and with the integration I only can control, speed (that is in percentages, and should be 8 steps), presets, oscilatting (but not the angles, that can be controlled using the Dreo's app, fox example 30degrees, 45, etc) and the the panel sound.

Would be great if the integration allows us to control the child lock, the oscilatting degrees and also de d-pad.

**Comment by JeffSteinbok** [comment]
I'm pretty sure there is already an ask open for degree of oscillation.  
Control position should be there; if it's missing for your specific fan, can you do me a favor and open a seperate issue.  
I'm trying to disambiguate between the open issues.
