### ISSUE TITLE
Dreo Smart Humidifier

### ISSUE THREAD

**Issue by raptor464** [JeffSteinbok/hass-dreo#60]
Are there any plans to support DREO Smart Humidifier, Model # HM311S

https://www.amazon.com/Dreo-Humidifier-Humidifiers-Ultrasonic-Nightlight/dp/B0CCVX6FSD?ref_=ast_sto_dp

**Comment by JeffSteinbok** [comment]
No immediate plans but perhaps. If it just acts like a fan perhaps.

Send me the diagnostics pls.

**Comment by raptor464** [comment]
Here is the diagnostics file:

[config_entry-dreo-c4f6978b7273aaf72105a86d1b4f1180.json.txt](https://github.com/JeffSteinbok/hass-dreo/files/12777529/config_entry-dreo-c4f6978b7273aaf72105a86d1b4f1180.json.txt)

**Comment by JeffSteinbok** [comment]
Ok, it's quite different than the fans.  So, right now, no, I'm going going to be able to add it. 
I may be able to give you a private drop that contains power on/off and you can tell me if it works for you.

**Comment by tensiondriven** [comment]
+1 for HM311S.

My ideal needs would be (and in order of importance):
- Get sensor data (current humidity)
- Turn on / off
- Set speed (Low/Med/High)

The ability to set a target humidity, control the internal light/illumination, control the display, or control sleep mode is less important to me.

**Comment by asheroto** [comment]
Hey I'm interested in this as well! Same model. I'm willing to help contribute to the code base so will look at this closer tomorrow.

**Comment by asheroto** [comment]
Finally had a chance to look at it and was able to capture some debug info. (also submitted a PR!)

I'm not sure if this will give you any more information, but thought I'd share anyway.

Here is the log:
[log.txt](https://github.com/JeffSteinbok/hass-dreo/files/14122903/log.txt)

And here is the diagnostics:
[config_entry-dreo.json](https://github.com/JeffSteinbok/hass-dreo/files/14122914/config_entry-dreo.json)

Also thought I'd mention, in case you don't already use it, [JSON Crack](https://jsoncrack.com/editor) is a wonderful way to visualize JSON data. They have a VS Code add-in as well.

**Comment by PapiOrtiz** [comment]
I just wanted to jump on the Humidifier train -- just got a HM713S.
Gonna see if I can figure out getting some logs + the JSON diagnostics.

**Comment by PapiOrtiz** [comment]
This was a fun project to figure - and turned out to be a lot easier than I expected.
The docs attached below are for the following Dreo Humidifier.
      Model: DR-HHM003S
      Series Name: HM713S/HM813S

Here is the config entry for the Humidifier:
[config_entry-dreo diagnostics-5a43b239033815df280aced23abaa2c4.json](https://github.com/user-attachments/files/16045766/config_entry-dreo.diagnostics-5a43b239033815df280aced23abaa2c4.json)

Here are the Debug Logs for all the functions I called to the Device -- I spaced them out so it's easier to read.
Let me know if you have any questions on what I did vs. the command reported.
[Dreo Debug logs - clean.txt](https://github.com/user-attachments/files/16045778/Dreo.Debug.logs.-.clean.txt)


Last - I saw in the config entry (line 313) that it can report when the humidifier needs to be cleaned.
I didn't see it in the logs, but if this could be pulled in, that would be awesome.


Thanks again for the help & let me know if there's anything I can do to make this easier on you.

**Comment by PapiOrtiz** [comment]
For added context, I've also attached some screenshots of how the device operates from within the app.
_
_
**_Device Controls - Auto Mode_**

![Controls_Auto](https://github.com/JeffSteinbok/hass-dreo/assets/132533774/a46f46c8-9ff3-452d-b034-697ab688a81e)

**_Device Controls - Manual Mode_**

![Controls_Manual](https://github.com/JeffSteinbok/hass-dreo/assets/132533774/953313b5-ff72-4bf3-b93d-eafe3d2f1504)

**_Device Controls - Sleep Mode_**
![Controls_Sleep](https://github.com/JeffSteinbok/hass-dreo/assets/132533774/96f04c1c-cb6c-4495-8f5a-dc9121229927)


**_Device Entities - Humidity + Filter Life_**

![Device Entities_Humidity + Filter Life](https://github.com/JeffSteinbok/hass-dreo/assets/132533774/f95710c9-95df-47c7-aece-d0e13a6f7a98)

**_Device Entities - Cleaning Reminder_**

![Device Entities_Cleaning Reminder](https://github.com/JeffSteinbok/hass-dreo/assets/132533774/af7d8555-d888-4fc4-9e71-ac6ba97083f8)

**Comment by asheroto** [comment]
I have the HM311S, same as the OP, and the app you mentioned looks the same, except my model does not have a "Warm Mist" feature. Let me know if I can provide any additional information or test a beta version.

**Comment by jprocket45** [comment]
It has been a while but I have the new HM524S and would love to see humidifiers added,  not sure if this is dead but figured I would say something as well to show more interest!!

**Comment by droolingtaz** [comment]
I just purchased a HM311S. It would be really awesome to be able to automate it with my Home Assistant.

**Comment by JeffSteinbok** [comment]
I need an additional log from someone with a humidifier.
Sync the attached branch into HA and run Diagnostics.

Alternatively, if you have a Python installation...
Just change the username/password

```
import time
import sys
import importlib.util
spec = importlib.util.spec_from_file_location("pydreo", "custom_components/dreo/pydreo/__init__.py")
pydreo = importlib.util.module_from_spec(spec)
sys.modules["pydreo"] = pydreo
spec.loader.exec_module(pydreo)
import logging
import asyncio
import threading
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

dreo = pydreo.PyDreo(username='x', 
    password='y'
    )
dreo.login()
dreo.enabled = True
dreo.load_devices()
```

**Comment by JeffSteinbok** [comment]
Specifically I need the JSON response from the GetDeviceState call. 

The branch may actually partially work too.

**Comment by jprocket45** [comment]
[config_entry-dreo-5f32b88582efd2df9ea5fa282dbe0592.json](https://github.com/user-attachments/files/16947426/config_entry-dreo-5f32b88582efd2df9ea5fa282dbe0592.json)

let me know if this helps!

**Comment by novamcgurk** [comment]
Just bought an ‎DR-HHM001S and would be very interested as well.

**Comment by JeffSteinbok** [comment]
> [config_entry-dreo-5f32b88582efd2df9ea5fa282dbe0592.json](https://github.com/user-attachments/files/16947426/config_entry-dreo-5f32b88582efd2df9ea5fa282dbe0592.json)
> 
> let me know if this helps!

This doesn't have what I need unfortunately.  Are you able to use HACS to install from this specific branch?  There is a service to call where you can pass in the commit hash to install from therem.

**Comment by JeffSteinbok** [comment]
> Just bought an ‎DR-HHM001S and would be very interested as well.
> 
> [config_entry-dreo-01J7EB5H63BRRSCDK3Q67MQJ1W.json](https://github.com/user-attachments/files/16947833/config_entry-dreo-01J7EB5H63BRRSCDK3Q67MQJ1W.json)

Thanks!  Can you please do that with the latest commit from the attached branch, or the python script above?

**Comment by novamcgurk** [comment]
Hope i used the python script the right way, this is what i got. (removed username and password informations)
[dreo_py_export.txt](https://github.com/user-attachments/files/16961529/dreo_py_export.txt)

**Comment by JeffSteinbok** [comment]
You did. Thanks. 

If you're comfortable trying out the integration from that branch, there is a decent chance it works at least partially for your device. Let me know.

**Comment by JeffSteinbok** [comment]
Please check out 1.1.0b1 and let me know how it works.
Once you confirm it works, let me know and I'll promote.

**Comment by jprocket45** [comment]
I am unsure if this was meant for all humidifiers but I checked out 1.1.0b1 as of now it recognizes my Humidifier but gives only the Panel Sound in controls, will wait to see if @novamcgurk has any better luck since they have a different model and you got the txt from them.

**Comment by PapiOrtiz** [comment]
Hi @JeffSteinbok 

Similar to above comment, i have a different model Humidifier (HM713S) and the device pulled in now, but only Panel Sound is available. 

Aside from this, the below errors are now appearing in my Logs. 
_________________
This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/dreo/pydreo/__init__.py:20
integration: Dreo (documentation, issues)
First occurred: 9:43:22 AM (1 occurrences)
Last logged: 9:43:22 AM

/config/custom_components/dreo/pydreo/pydreotowerfan.py:75: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
_________________
Source: custom_components/dreo/pydreo/__init__.py:21

/config/custom_components/dreo/pydreo/pydreoaircirculator.py:76: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
_________________
Source: custom_components/dreo/pydreo/__init__.py:22

/config/custom_components/dreo/pydreo/pydreoceilingfan.py:63: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
_________________
Source: custom_components/dreo/pydreo/__init__.py:23

/config/custom_components/dreo/pydreo/pydreoairpurifier.py:55: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (preset_modes.count is 0):
_________________
Source: custom_components/dreo/pydreo/__init__.py:27

/config/custom_components/dreo/pydreo/pydreohumidifier.py:57: SyntaxWarning: "is" with 'int' literal. Did you mean "=="? if (modes.count is 0):

**Comment by JeffSteinbok** [comment]
Found it - one of the parts I can't easily test without the device.  1.1.0b2 coming very soon

**Comment by JeffSteinbok** [comment]
We can, but I’m going to do some other work before cleaning %.  Assuming all the core humidifier functions work, I’ll push this release out.

Please file a new issue for the other ancillary features you feel are needed.

-Jeff

On Sep 12, 2024, at 10:08 AM, jprocket45 ***@***.***> wrote:

﻿

this works! I know how on/off then manual auto/sleep with humidity lvl adjustment is it possible to add the cleaning reminder percent?? if not that is fine not sure what can all be brought in and can't thank you!!
image.png (view on web)<https://github.com/user-attachments/assets/e22c93d9-7ff5-4430-bbce-8fb821158b55>
image.png (view on web)<https://github.com/user-attachments/assets/d9a24a52-be57-4c79-83b6-31674fe099bd>

**Comment by jprocket45** [comment]
after testing things out I can confirm everything works but one thing is a bit buggy if you are in manual mode you have to go to auto to go to sleep mode it will not go manual to sleep will wait for others to respond as well.

**Comment by JeffSteinbok** [comment]
Are you saying you can't transition from "Manual" to "Sleep" mode?
Are you able to do this from the Dreo app itself?
If so, can you please enable logging, then perform the actions in the Dreo app and send me the relevant portions of the logs?

**Comment by jprocket45** [comment]
I am sorry I can specify better now that I am home and trying it all out basically what is going on is when I push

Dreo App  Manuel = Sleep in HA

Dreo App Auto = Manuel HA

Dreo App Sleep =  Auto in HA

I am trying to help and apologize that the last report didn't explain anything I hope this explains better if you need me to still enable logging and send a report just let me know. I am far from good at this but working threw it and will try to figure out how to do logging if needed.

**Comment by JeffSteinbok** [comment]
Ok, I'll see if I have what I need, but logs wouldn't hurt.  Wonder if I messed up some number mappings.

**Comment by ryakat** [comment]
I have DR-HHM001S and I can confirm there's something going on with the sleep function drop down. If I am in manual mode and then select Sleep the toggle will stay on Sleep for a second and then revert back to Manual. It will also do the same behavior with Auto, if you try to go to Sleep from Auto it will stay on Sleep for a moment and then toggle back to Auto.

**Comment by jprocket45** [comment]
@ryakat are ur buttons messed up as well though? I am trying to help Jeff with logs if you know how to provide logs better please help since I am not sure what I am doing. @JeffSteinbok I enabled debugging is that the file you need?

**Comment by raptor464** [comment]
OP here. Just updated to the latest version in HACS and both of my HM311S humidifiers are showing up in HA. I haven't tried messing with them yet but they are showing up and I'm seeing the statuses now. I'll try messing with them to see if the controls work too.

**Comment by JeffSteinbok** [comment]
Think I figured out what may be wrong with modes.

**Comment by JeffSteinbok** [comment]
See 1.1.0b3

**Comment by jprocket45** [comment]
after doing tests on 1.1.0b3 I can confirm modes are fixed correctly and as I was thinking since those are fixed the sleep mode is also fixed that was reported, it appears everything is up and working from what I have tried.

**Comment by novamcgurk** [comment]
Hi, haven´t had time to test it but did the test with 1.1.0b2 and now with 1.1.0b3 and everything seems to be working as intended with my DR-HHM001S. Than you so much. 🙏

**Comment by asheroto** [comment]
Using a Dreo HM311S and can confirm it works. Thanks for your hard work @JeffSteinbok!!!

I'm guessing these are the other things on the todo list?

- Schedule support
- Filter reminder support (not applicable on all models, including mine)
- Cleaning reminder support?

**Comment by JeffSteinbok** [comment]
The latter two, maybe.
The Schedule, no, use HA for that
________________________________

**Comment by asheroto** [comment]
Understood, that makes sense.

If you set a up a sponsors section I'll contribute to your work as a thank you. 😊

https://docs.github.com/en/sponsors/getting-started-with-github-sponsors/about-github-sponsors

**Comment by JeffSteinbok** [comment]
Appreciate that, I’ll look into it.
Feel free to file a new Issue for the specific features you’re interested in, that way people can grab them.

**Comment by asheroto** [comment]
Humidifier shows unavailable now, not sure what happened. Wondering if an update knocked it out. Created issue #211. Thank you sir!
