### ISSUE TITLE
Dreo Atom One space heater DR-HSH004S support

### ISSUE THREAD

**Issue by Boston777** [JeffSteinbok/hass-dreo#61]
this smart heater has 5 modes total. A heat mode or fan only mode. In fan mode there aren't any speed options. In the heat mode there are 4 modes, H1, H2, H3 for 3 different wattage outputs and fan speeds. then an eco mode tied to a temperature value where the heater will auto adjust wattage and fan speed and turn off when temperature is achieved. It also supports oscillation.

I would love to be able to have this integration working if possible, and I'm more than happy to send any logs you need and a huge thank you in advance!

**Comment by tbennett6421** [comment]
+1

**Comment by andy-cooper** [comment]
@Boston777 and @tbennett6421 - I've actually just created a PR for supporting the Atom One space heater. It was a fair amount of work, so I suspect it may take a while for @JeffSteinbok to be able to fully review it and merge it in. In the meantime, if you're somewhat technically minded, my fork of it - https://github.com/andy-cooper/hass-dreo - has my code in it, and I am using it in my HA installation. I've modeled it as a climate device, so you can get the nice little climate dial with support for ECO, H1, H2, H3, fan-only, oscillating mode and so on. You can set the temperature in ECO mode. The various other bits like panel LED on/off, panel sound on/off, etc. are all also supported via separate entities.

Here are some images:


<img width="585" alt="Screenshot 2024-02-04 at 11 26 52 PM" src="https://github.com/JeffSteinbok/hass-dreo/assets/3037419/39149fb6-92b6-4e4c-b244-f384c40b1505">
<img width="589" alt="Screenshot 2024-02-04 at 11 26 40 PM" src="https://github.com/JeffSteinbok/hass-dreo/assets/3037419/685fb04e-184a-4834-bc0f-08307b8fb505">
<img width="586" alt="Screenshot 2024-02-04 at 11 26 29 PM" src="https://github.com/JeffSteinbok/hass-dreo/assets/3037419/23ac5d17-2034-4706-80d1-1212532ad3d6">
<img width="495" alt="Screenshot 2024-02-04 at 11 26 07 PM" src="https://github.com/JeffSteinbok/hass-dreo/assets/3037419/47a175eb-9098-4108-b0fb-280497168334">

**Comment by andy-cooper** [comment]
The PR I'm referring to is this one - https://github.com/JeffSteinbok/hass-dreo/pull/71

**Comment by tbennett6421** [comment]
I've installed this and it appears to work perfectly for my `DR-HSH004S`

**Comment by vern42** [comment]
@JeffSteinbok - would you consider making a new release now that the heaters are supported?

**Comment by JeffSteinbok** [comment]
This is done.
