### ISSUE TITLE
Air Purifier (Macro Pro S)

### ISSUE THREAD

**Issue by cameronbowe** [JeffSteinbok/hass-dreo#63]
I'd love support for Air Purifiers, specifically the Macro Pro S (DR-HAP002S).

It uses the following keys and values:

"aq" key with values 1-3 (1 Excellent, 2 Moderate, 3 Poor) - This is for air quality.
"windlevel" key with values 1-19 - This is for speed.
"mode" key with values "manual", "sleep", "turbo", "auto-regular" and "auto-silent" - Mode manual only happens when speed is selected, the auto modes are changed when you select "Standard" or "Soft" quiet mode, the auto mode automatically adjusts the fan speed based off the air quality.
"childlockon" key with values True or False - This disables/enables the ability to press buttons on the device.
"ledalwayson" key with values True or False - This enables/disables the light on the device which displays the air quality.
"muteon" key with values True or False - This enables/disables the sounds the device makes.

If you need anything else, I'd love to help you out as your project is fantastic.

**Comment by imthisguymike** [comment]
I second this, I would like to have this added as well, as I have one of these.

**Comment by Monsterray** [comment]
I third this, keeping track of air quality with this would be very nice! I also provided log information in #76.

**Comment by JeffSteinbok** [comment]
If you're able to test out this branch via a commit hash in HACS, let me know if it works.
I may refactor this completely still; not sure.

**Comment by JeffSteinbok** [comment]
@Monsterray  can you please check if the attached branch works?

**Comment by Monsterray** [comment]
I have tried the newest version of the main branch and I am not seeing my Macro Pro S as a device still. I am still seeing my Air Circulator still though. How can I help?

**Comment by cameronbowe** [comment]
> I have tried the newest version of the main branch and I am not seeing my Macro Pro S as a device still. I am still seeing my Air Circulator still though. How can I help?

On the same page, I was hoping after so much time and others requesting it there was a chance it'd work, but nada.
