### ISSUE TITLE
DREO Cruiser Pro T3

### ISSUE THREAD

**Issue by RPMarcello** [JeffSteinbok/hass-dreo#66]
Morning,

I recently purchased a DR-HTF008S Silver from Amazon specifically to use it thru HA.  After reviewing the integration readme, it seems straight forward by just adding it thru HACS.

I'm not sure what needs to be done and I have not done any programming.

**Comment by JeffSteinbok** [comment]
Should already be supported.  Install the integration via HACS, then go to add the device.  You'll need to login, and it should detect it.
