### ISSUE TITLE
Unable to login to dreo server

### ISSUE THREAD

**Issue by NDeshmukh516** [JeffSteinbok/hass-dreo#67]
I even changed my password and tried signing in with a new one, however it seems to always fail to connect to the dreo server now.

**Comment by JeffSteinbok** [comment]
Yup, something changed very recently.  Am debugging presently.

**Comment by JeffSteinbok** [comment]
If anyone is able to get a packet capture from the Android app let me know. I'm having some challenges.

**Comment by btehan** [comment]
[PCAPdroid_07_Jan_17_33_49.pcap.txt](https://github.com/JeffSteinbok/hass-dreo/files/13855273/PCAPdroid_07_Jan_17_33_49.pcap.txt)


I had to add.txt to get it to upload to GitHub.  I generated that using PCAPdroid from Fdroid.  Hopefully that works for you.

**Comment by JeffSteinbok** [comment]
Thanks, but this isn't showing the api calls, as it's over SSL.  I'm still working on getting the app to run on an Android emulator so I can run Frida and get around the cert pinning. :(

**Comment by jphoke** [comment]
Ok -- at least I'm not losing my mind ... was working then I restarted HA for the update and it went sideways ... Let me see if I can get something when at work -- I'm all iOS but maybe one of my engineers can do something on an android device

**Comment by JeffSteinbok** [comment]
So, we're a bit stuck - the hombridge owner is also having the same issue with the emulator.  We're not sure if the android app is busted or if there is something with the emulator.  If anyone has an Android device, are you able to install Dreo and even navigate to the "Create Account" page successfully?

**Comment by btehan** [comment]
![Screenshot_20240108-114332](https://github.com/JeffSteinbok/hass-dreo/assets/62584008/757c276e-338d-43dd-b369-c9c7de0dc812)
I just reinstalled the app and was able to navigate to that page successfully on my Pixel.   Is that what you're talking about?

**Comment by JeffSteinbok** [comment]
Yup.  I can't get to that page on the emulator. :(

**Comment by JeffSteinbok** [comment]
Resolved in v0.6.2

**Comment by btehan** [comment]
Works!   Thank you =⁠-)
