### ISSUE TITLE
Add new fan DR-HAF003S

### ISSUE THREAD

**Issue by mortenjensen64** [JeffSteinbok/hass-dreo#7]
DR-HAF003S 
8 speeds 
yes, has oscillation

preset modes: normal, natural, sleep, auto, turbo, custom 
yes, temperature is supported

**Comment by JeffSteinbok** [comment]
Can you please send me the diagnostics from the integration? 
It's on /config/integrations/integration/dreo, in the "..." menu.

**Comment by mortenjensen64** [comment]
@JeffSteinbok - I'm using docker / core, I don't think I have the /config.../dreo available.  I did set the logging to debug and was able to run through the different commands from the Dreo app.  I added comments to the log file so you can see what action was done in the Dreo app.  Logfile is attached.  Please let me know if you need additional data.

[home-assistant_2023-07-06T12-09-15.105Z.log](https://github.com/JeffSteinbok/hass-dreo/files/11968618/home-assistant_2023-07-06T12-09-15.105Z.log)

**Comment by mortenjensen64** [comment]
Thanks for the clarification, I think I got it.  Attached is the diagnostics file.  
HA- 2023.7.0
Dreo- 0.0.2
 
[config_entry-dreo-ac1ded7c995bab0f556e3cab26579bb2.json.txt](https://github.com/JeffSteinbok/hass-dreo/files/11970099/config_entry-dreo-ac1ded7c995bab0f556e3cab26579bb2.json.txt)

**Comment by FaultyLine** [comment]
Hi there! I have the same model fan - @JeffSteinbok, Did you get everything you needed from @mortenjensen64 or is there additional info / logs I may be able to contribute? 

Thanks!

**Comment by JeffSteinbok** [comment]
Supported in version 0.2.0b2.
Horizontal oscillation only
