### ISSUE TITLE
PolyFan 513S Air Circulator Fan

### ISSUE THREAD

**Issue by shedman214** [JeffSteinbok/hass-dreo#73]
[Link](https://us.dreo.com/products/dreo-polyfan-max-s-air-circulator-fan?variant=43333933236386)
Model - in the format above: PolyFan - 513S
Number of speeds the fan supports (not including "off"): 8-built in speeds, 12h on/off timer
Does the fan support oscillating?: 120° horizontal, 105° vertical (omni-directional oscillation)
What preset modes are supported?: Turbo Mode, Normal Mode, Natural Mode, Sleep Mode and Custom Mode
Is temperature supported? I don't know. I believe not

**Comment by JeffSteinbok** [comment]
Can you please install & configure the add in and share logs?  Should report the details we need to add it.

**Comment by JeffSteinbok** [comment]
Should be in 0.7.1

**Comment by modem7** [comment]
> Should be in 0.7.1

Heya,

Thank you!

Almost perfect, but it seems that the speed setting is still omitted from the avaliable/exposed sensors.
