### ISSUE TITLE
Add Support for WH729S Heater

### ISSUE THREAD

**Issue by reynolds-adam** [JeffSteinbok/hass-dreo#75]
Model: WH729S (This is the same heater as WH719S except is has a safety plug)
Speeds: Not sure. Amazon listing says 3, but I'm not able to change the speed anywhere in the app. The 3 might refer to the 3 heat modes. 
Oscillation: Yes
Preset Modes: H1 (Heat level 1), H2, H3, Eco, and Fan only
Temperature: Yes, in eco mode you can set the temp.

I'm happy to help if you have any questions. I really appreciate your work on this!

**Comment by reynolds-adam** [comment]
FYI, Temperate ranges from 41 degrees to 95.

**Comment by ptmgcorp** [comment]
@reynolds-adam That right there is a DR-HSH009S. Its already supported. Just make sure your downloading the main branch.

**Comment by JeffSteinbok** [comment]
I've pushed 0.6.3 which should have this in it.  Should be able to update from HACS.
