### ISSUE TITLE
Support for MultiComfort Series 2-in-1 (Fan/Purifier) - DR-HTF010S

### ISSUE THREAD

**Issue by jh20001** [JeffSteinbok/hass-dreo#80]
Any plans to add this one? https://www.pocnetwork.net/product-reviews/embargo-03-26-dreo-multicomfort-series-2-in-1-air-purifying-tower-fan-mc710/

It sounds cool, but I haven't jumped on one just yet. Waiting for a much better sale as I don't "need" it as much as it would be nice to have. That one might be a little tricky since it has features shared between two types of products. 

Model Number: DR-HTF010S
Number of speeds the fan supports: 12
Does the fan support oscilating?: Yes
What preset modes are supported? 
    - The fan portion: Normal, Sleep, Auto, Breeze
    - The purifier portion: Auto, 1, 2, 3
Is temperature supported?: Yes

I know it isn't much since I don't physically own one (yet) to play with, so this is all based on what I could find in that story or the product's page, as well as various images of the app or specs.

**Comment by poland153** [comment]
I have purchased one of these after I bought a regular fan that worked great with hass-dreo.

Uploading the full HA logs and hacs-dreo json.

[config_entry-dreo-887f6bdf61b011037b5a58d442fa1dc0.json](https://github.com/JeffSteinbok/hass-dreo/files/14900598/config_entry-dreo-887f6bdf61b011037b5a58d442fa1dc0.json)
[home-assistant_2024-04-08T03-37-22.296Z.log](https://github.com/JeffSteinbok/hass-dreo/files/14900599/home-assistant_2024-04-08T03-37-22.296Z.log)

**Comment by amulla928** [comment]
I just bought this fan, I was trying to figure out how to get the logs but i'm stumped, im new at this.
I have the Dreo plugin running on HOOBS, DREO app on iOS, and a windows computer.  Any help to get the logs would be greatly appreciated.

**Comment by poland153** [comment]
> I just bought this fan, I was trying to figure out how to get the logs but i'm stumped, im new at this. I have the Dreo plugin running on HOOBS, DREO app on iOS, and a windows computer. Any help to get the logs would be greatly appreciated.

The instructions are in the readme https://github.com/JeffSteinbok/hass-dreo?tab=readme-ov-file#debugging

**Comment by JeffSteinbok** [comment]
Should be in 0.7.1
