### ISSUE TITLE
UK fan not showing speed options

### ISSUE THREAD

**Issue by benjconrad** [JeffSteinbok/hass-dreo#83]
I think I read that a Github issue is easier for you than adding to never ending threads.
Partly based on the availability of this integration (and thank you very much for contributing it) I purchased a Dreo fan from amazon.co.uk. The model number listed https://www.amazon.co.uk/dp/B0BSNCGBDH here is `CF511S`. The air circulator was detected by the integration as DR-HAF001S, which is indeed the number on the base of the unit.
The only issue I am having is that I can not control the speed of the fan from Home Assistant. I only have four entities listed for the device - On/Off, Oscillation, Panel Sound and Temperature. Is there a way I can add the additional controls? Apologies if I am missing something obvious.

**Comment by lukedemi** [comment]
I just bought the same fan and have the same problem. It looks like the fan speeds are there but yeah I can't control speed or  presets either.

https://github.com/JeffSteinbok/hass-dreo/blob/2d6f84c83fb2afa19c419637ec6df47288fff7bd/custom_components/dreo/pydreo/models.py#L74

**Comment by JeffSteinbok** [comment]
Speed shouldn't show as a seperate control; it should be part of the Fan itself.
![image](https://github.com/JeffSteinbok/hass-dreo/assets/7330767/a818e409-031d-4108-a5e0-bc87c71f6422)

If still not working, pull a diagnostic and screenshots and re-open
