### ISSUE TITLE
DR-HTF007S missing swing and preset modes

### ISSUE THREAD

**Issue by seaton88** [JeffSteinbok/hass-dreo#84]
Hi, and thanks for the work!

I recently bought a DR-HTF007S for this integration, but it's missing oscillation/swing attributes and preset modes in HA. Tried deleting hacs integration and starting again, but no joy.

Has anyone else had this issue? Believe these features should be supported with this integration?

**Comment by jrb80** [comment]
I have the same issue, did you find a solution?
