### ISSUE TITLE
Homekit Modes from Switch to Outlets

### ISSUE THREAD

**Issue by ArkhanDev** [JeffSteinbok/hass-dreo#85]
Is it possible to change the Modes from Switches to Outlets? A demonstration is below
![IMG_3153](https://github.com/JeffSteinbok/hass-dreo/assets/97233088/518348e3-5b7e-4dee-8430-5e56ae5b041f)

I think it would be way easier to use, as its just a click

**Comment by JeffSteinbok** [comment]
I'm just using the default Fan type in HA. 
The settings on it are Switches, which is correct.  Outlets doesn't seem right.
