### ISSUE TITLE
Add Support for Ceiling Fan DR-HCF001S / CLF521S

### ISSUE THREAD

**Issue by jasonnovak** [JeffSteinbok/hass-dreo#86]
A Dreo ceiling fan I got from Amazon, it's not listed on their site yet

12 different speed levels and three wind modes (Natural, Normal, Sleep)

Dreo 52" Smart Ceiling Fan with Lights, 12 Speeds & 3 Fan Modes, Quiet DC Motor, Stepless Color Temperature & Dimmable Ceiling Fans Indoor, Remote/APP/Alexa Control, 12H Timing,White 

stepless brightness (1% to 100%) and light temperatures (from 2700K warm yellow to 6500K cool white). 

 switch the wind direction of the ceiling fan from the downward airflow during the summer to the upward airflow during the winter.
[config_entry-dreo-7fc820b62e206e89029c3455cbf15b62(1).json](https://github.com/JeffSteinbok/hass-dreo/files/15144764/config_entry-dreo-7fc820b62e206e89029c3455cbf15b62.1.json)

**Comment by JeffSteinbok** [comment]
Done except for light.
Light tracked in #143
