### ISSUE TITLE
‎DR-HTF009S support?

### ISSUE THREAD

**Issue by Karmxh** [JeffSteinbok/hass-dreo#88]
device is not listed but the previous version is, just wondering if support could be added as I can't find a link to buy older models on amazon

**Comment by jprocket45** [comment]
just go on Dreos website just bought a HTF007 for 68 bucks amazon is not just your only friend :) lol unless you want to wait I understand the newer models are usually better on upgrades, all up to you, I do hope they keep adding more devices and newer ones :)
