### ISSUE TITLE
DR-HTF002S problems 

### ISSUE THREAD

**Issue by styphonthal** [JeffSteinbok/hass-dreo#90]
I have the tower fan, DR-HTF002S:

1. It turns on when pressing HA power button but on home assistant it kicks back to "off" yet the dreo app says on, and the fan is physically on 
2. the HA off button/switch doesn't work 
3. odd reporting on HA about current state and setting. I've found setting fan speed to 0% turns it physical off and off on the dreo app, but still says on at the previous percentage on the home assistant app

**Comment by VOSsec** [comment]
#87 This error is already known and has nothing to do with your model.
