### ISSUE TITLE
Add Support for DR-HTF009S 

### ISSUE THREAD

**Issue by ahmed-mohamed01** [JeffSteinbok/hass-dreo#95]
Model: DR-HTF009S 
Number of Speeds: 9
Does the fan support oscillating: Yes, 90 degrees, horizontal. 
What preset modes are supported: Normal, Natural, Sleep, Auto. 
Is temperature supported: Yes

Thank you for the hard work! Please let me know if you need debug logs.

**Comment by ahmed-mohamed01** [comment]
Turns out the changes needed to get it working was very minor, got it working on my HA. 

![image](https://github.com/JeffSteinbok/hass-dreo/assets/156935141/a955f55e-6609-4828-b8e7-b5f3499e8470)


Pull request made, thank you for the plugin!

**Comment by JeffSteinbok** [comment]
Committed to Main
